// Code generated by goctl. DO NOT EDIT.
package types

type CancelOrderReq struct {
	OrderID      string `json:"order_id"`
	CancelReason string `json:"cancel_reason,optional"`
}

type CancelOrderResp struct {
	OrderID string `json:"order_id"`
}

type CreateOrderReq struct {
	PreOrderID    string `json:"pre_order_id"`
	CouponID      string `json:"coupon_id,optional"`
	AddressID     int32  `json:"address_id"`
	PaymentMethod int32  `json:"payment_method"` // 1-WECHAT_PAY 2-ALIPAY
}

type GetOrderReq struct {
	OrderID string `json:"order_id"`
}

type ListOrdersReq struct {
	Statuses []int32 `json:"statuses,optional"` // 订单状态过滤列表
	Page     int32   `json:"page,default=1"`
	PageSize int32   `json:"page_size,default=10"`
}

type ListOrdersResp struct {
	Orders []OrderResp `json:"orders"`
}

type OrderAddressResp struct {
	AddressID       uint64 `json:"address_id"`
	RecipientName   string `json:"recipient_name"`
	PhoneNumber     string `json:"phone_number"`
	Province        string `json:"province"`
	City            string `json:"city"`
	DetailedAddress string `json:"detailed_address"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	OrderID         string `json:"order_id"`
}

type OrderDetailResp struct {
	Order   OrderResp        `json:"order"`
	Items   []OrderItemResp  `json:"items"`
	Address OrderAddressResp `json:"address"`
}

type OrderItemResp struct {
	ItemID      string `json:"item_id"`
	ProductID   uint64 `json:"product_id"`
	Quantity    uint64 `json:"quantity"`
	ProductName string `json:"product_name"`
	ProductDesc string `json:"product_desc"`
	UnitPrice   string `json:"unit_price"`
}

type OrderResp struct {
	OrderID        string `json:"order_id"`
	PreOrderID     string `json:"pre_order_id"`
	UserID         uint32 `json:"user_id"`
	PaymentMethod  int32  `json:"payment_method"`
	TransactionID  string `json:"transaction_id"`
	PaidAt         int64  `json:"paid_at"`
	OriginalAmount string `json:"original_amount"`
	DiscountAmount string `json:"discount_amount"`
	PayableAmount  string `json:"payable_amount"`
	PaidAmount     string `json:"paid_amount"`
	OrderStatus    int32  `json:"order_status"`
	PaymentStatus  int32  `json:"payment_status"`
	Reason         string `json:"reason"`
	ExpireTime     string `json:"expire_time"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}
