// Code generated by goctl. DO NOT EDIT.

package order

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemsFieldNames          = builder.RawFieldNames(&OrderItems{})
	orderItemsRows                = strings.Join(orderItemsFieldNames, ",")
	orderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemsFieldNames, "`order_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderItemsModel interface {
		Insert(ctx context.Context, data *OrderItems) (sql.Result, error)
		FindOne(ctx context.Context, orderId string) (*OrderItems, error)
		Update(ctx context.Context, data *OrderItems) error
		Delete(ctx context.Context, orderId string) error
	}

	defaultOrderItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderItems struct {
		OrderId     string    `db:"order_id"`     // 预订单ID
		ProductId   uint64    `db:"product_id"`   // 商品ID
		Quantity    uint64    `db:"quantity"`     // 数量
		Price       int64     `db:"price"`        // 当时单价（分）
		ProductName string    `db:"product_name"` // 商品名称
		ProductDesc string    `db:"product_desc"` // 商品描述
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newOrderItemsModel(conn sqlx.SqlConn) *defaultOrderItemsModel {
	return &defaultOrderItemsModel{
		conn:  conn,
		table: "`order_items`",
	}
}

func (m *defaultOrderItemsModel) Delete(ctx context.Context, orderId string) error {
	query := fmt.Sprintf("delete from %s where `order_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, orderId)
	return err
}

func (m *defaultOrderItemsModel) FindOne(ctx context.Context, orderId string) (*OrderItems, error) {
	query := fmt.Sprintf("select %s from %s where `order_id` = ? limit 1", orderItemsRows, m.table)
	var resp OrderItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemsModel) Insert(ctx context.Context, data *OrderItems) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, orderItemsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.Quantity, data.Price, data.ProductName, data.ProductDesc)
	return ret, err
}

func (m *defaultOrderItemsModel) Update(ctx context.Context, data *OrderItems) error {
	query := fmt.Sprintf("update %s set %s where `order_id` = ?", m.table, orderItemsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.Quantity, data.Price, data.ProductName, data.ProductDesc, data.OrderId)
	return err
}

func (m *defaultOrderItemsModel) tableName() string {
	return m.table
}
