// Code generated by goctl style. DO NOT EDIT.

package order

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	outboxMessagesFieldNames          = builder.RawFieldNames(&OutboxMessages{})
	outboxMessagesRows                = strings.Join(outboxMessagesFieldNames, ",")
	outboxMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(outboxMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	outboxMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(outboxMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	outboxMessagesModel interface {
		Insert(ctx context.Context, data *OutboxMessages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*OutboxMessages, error)
		Update(ctx context.Context, data *OutboxMessages) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOutboxMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OutboxMessages struct {
		Id            uint64         `db:"id"`              // 主键
		MessageId     string         `db:"message_id"`      // 消息唯一ID
		EventType     string         `db:"event_type"`      // 事件类型
		Topic         string         `db:"topic"`           // MQ topic
		MessageKey    string         `db:"message_key"`     // MQ message key
		Payload       string         `db:"payload"`         // 消息体
		Status        int64          `db:"status"`          // 0-pending 1-sending 2-sent 3-failed
		RetryCount    int64          `db:"retry_count"`     // 已重试次数
		MaxRetryCount int64          `db:"max_retry_count"` // 最大重试次数
		NextRetryAt   time.Time      `db:"next_retry_at"`   // 下次可重试时间
		LockedUntil   sql.NullTime   `db:"locked_until"`    // 发送锁过期时间
		LastError     sql.NullString `db:"last_error"`      // 最近一次错误
		SentAt        sql.NullTime   `db:"sent_at"`         // 发送成功时间
		CreatedAt     time.Time      `db:"created_at"`      // 创建时间
		UpdatedAt     time.Time      `db:"updated_at"`      // 更新时间
	}
)

func newOutboxMessagesModel(conn sqlx.SqlConn) *defaultOutboxMessagesModel {
	return &defaultOutboxMessagesModel{
		conn:  conn,
		table: "`outbox_messages`",
	}
}

func (m *defaultOutboxMessagesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOutboxMessagesModel) FindOne(ctx context.Context, id uint64) (*OutboxMessages, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", outboxMessagesRows, m.table)
	var resp OutboxMessages
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOutboxMessagesModel) Insert(ctx context.Context, data *OutboxMessages) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, outboxMessagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MessageId, data.EventType, data.Topic, data.MessageKey, data.Payload, data.Status, data.RetryCount, data.MaxRetryCount, data.NextRetryAt, data.LockedUntil, data.LastError, data.SentAt)
	return ret, err
}

func (m *defaultOutboxMessagesModel) Update(ctx context.Context, newData *OutboxMessages) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, outboxMessagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.MessageId, newData.EventType, newData.Topic, newData.MessageKey, newData.Payload, newData.Status, newData.RetryCount, newData.MaxRetryCount, newData.NextRetryAt, newData.LockedUntil, newData.LastError, newData.SentAt, newData.Id)
	return err
}

func (m *defaultOutboxMessagesModel) tableName() string {
	return m.table
}
