// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package conversation_summaries

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiConversationSummariesFieldNames          = builder.RawFieldNames(&AiConversationSummaries{})
	aiConversationSummariesRows                = strings.Join(aiConversationSummariesFieldNames, ",")
	aiConversationSummariesRowsExpectAutoSet   = strings.Join(stringx.Remove(aiConversationSummariesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiConversationSummariesRowsWithPlaceHolder = strings.Join(stringx.Remove(aiConversationSummariesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiConversationSummariesIdPrefix = "cache:aiConversationSummaries:id:"
)

type (
	aiConversationSummariesModel interface {
		Insert(ctx context.Context, data *AiConversationSummaries) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AiConversationSummaries, error)
		Update(ctx context.Context, data *AiConversationSummaries) error
		Delete(ctx context.Context, id string) error
	}

	defaultAiConversationSummariesModel struct {
		sqlc.CachedConn
		table string
	}

	AiConversationSummaries struct {
		Id                    string    `db:"id"`                       // 摘要ID
		ConversationId        string    `db:"conversation_id"`          // 会话ID
		UserId                uint64    `db:"user_id"`                  // 用户ID
		CoveredUntilCreatedAt time.Time `db:"covered_until_created_at"` // 已覆盖消息时间水位
		CoveredUntilMessageId string    `db:"covered_until_message_id"` // 已覆盖消息ID水位
		Summary               string    `db:"summary"`                  // 会话摘要
		KeyFacts              string    `db:"key_facts"`                // 稳定关键事实
		OpenTasks             string    `db:"open_tasks"`               // 未完成事项
		TokenCount            uint64    `db:"token_count"`              // 摘要估算Token
		CreatedAt             time.Time `db:"created_at"`
		UpdatedAt             time.Time `db:"updated_at"`
	}
)

func newAiConversationSummariesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAiConversationSummariesModel {
	return &defaultAiConversationSummariesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ai_conversation_summaries`",
	}
}

func (m *defaultAiConversationSummariesModel) Delete(ctx context.Context, id string) error {
	aiConversationSummariesIdKey := fmt.Sprintf("%s%v", cacheAiConversationSummariesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiConversationSummariesIdKey)
	return err
}

func (m *defaultAiConversationSummariesModel) FindOne(ctx context.Context, id string) (*AiConversationSummaries, error) {
	aiConversationSummariesIdKey := fmt.Sprintf("%s%v", cacheAiConversationSummariesIdPrefix, id)
	var resp AiConversationSummaries
	err := m.QueryRowCtx(ctx, &resp, aiConversationSummariesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiConversationSummariesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiConversationSummariesModel) Insert(ctx context.Context, data *AiConversationSummaries) (sql.Result, error) {
	aiConversationSummariesIdKey := fmt.Sprintf("%s%v", cacheAiConversationSummariesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, aiConversationSummariesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ConversationId, data.UserId, data.CoveredUntilCreatedAt, data.CoveredUntilMessageId, data.Summary, data.KeyFacts, data.OpenTasks, data.TokenCount)
	}, aiConversationSummariesIdKey)
	return ret, err
}

func (m *defaultAiConversationSummariesModel) Update(ctx context.Context, data *AiConversationSummaries) error {
	aiConversationSummariesIdKey := fmt.Sprintf("%s%v", cacheAiConversationSummariesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiConversationSummariesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ConversationId, data.UserId, data.CoveredUntilCreatedAt, data.CoveredUntilMessageId, data.Summary, data.KeyFacts, data.OpenTasks, data.TokenCount, data.Id)
	}, aiConversationSummariesIdKey)
	return err
}

func (m *defaultAiConversationSummariesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiConversationSummariesIdPrefix, primary)
}

func (m *defaultAiConversationSummariesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiConversationSummariesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAiConversationSummariesModel) tableName() string {
	return m.table
}
