// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: coupons.proto

package coupons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponType int32

const (
	CouponType_COUPON_TYPE_UNSPECIFIED    CouponType = 0 // 未指定
	CouponType_COUPON_TYPE_FULL_REDUCTION CouponType = 1 // 满减券
	CouponType_COUPON_TYPE_DISCOUNT       CouponType = 2 // 折扣券
	CouponType_COUPON_TYPE_FIXED_AMOUNT   CouponType = 3 // 立减券
)

// Enum value maps for CouponType.
var (
	CouponType_name = map[int32]string{
		0: "COUPON_TYPE_UNSPECIFIED",
		1: "COUPON_TYPE_FULL_REDUCTION",
		2: "COUPON_TYPE_DISCOUNT",
		3: "COUPON_TYPE_FIXED_AMOUNT",
	}
	CouponType_value = map[string]int32{
		"COUPON_TYPE_UNSPECIFIED":    0,
		"COUPON_TYPE_FULL_REDUCTION": 1,
		"COUPON_TYPE_DISCOUNT":       2,
		"COUPON_TYPE_FIXED_AMOUNT":   3,
	}
)

func (x CouponType) Enum() *CouponType {
	p := new(CouponType)
	*p = x
	return p
}

func (x CouponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponType) Descriptor() protoreflect.EnumDescriptor {
	return file_coupons_proto_enumTypes[0].Descriptor()
}

func (CouponType) Type() protoreflect.EnumType {
	return &file_coupons_proto_enumTypes[0]
}

func (x CouponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponType.Descriptor instead.
func (CouponType) EnumDescriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{0}
}

type CouponStatus int32

const (
	CouponStatus_COUPON_STATUS_UNSPECIFIED CouponStatus = 0 // 未指定或默认状态，用户领取优惠券后，可正常使用
	CouponStatus_COUPON_STATUS_LOCKED      CouponStatus = 1 // 用户点击结算时锁定，锁定期间其他订单不可重复使用
	CouponStatus_COUPON_STATUS_USED        CouponStatus = 2 // 支付成功确认，标记为已消耗
	CouponStatus_COUPON_STATUS_EXPIRED     CouponStatus = 3 // 超过有效期未使用，自动失效
	CouponStatus_COUPON_STATUS_REVOKED     CouponStatus = 4 // 管理员手动作废，强制失效（如活动终止）
)

// Enum value maps for CouponStatus.
var (
	CouponStatus_name = map[int32]string{
		0: "COUPON_STATUS_UNSPECIFIED",
		1: "COUPON_STATUS_LOCKED",
		2: "COUPON_STATUS_USED",
		3: "COUPON_STATUS_EXPIRED",
		4: "COUPON_STATUS_REVOKED",
	}
	CouponStatus_value = map[string]int32{
		"COUPON_STATUS_UNSPECIFIED": 0,
		"COUPON_STATUS_LOCKED":      1,
		"COUPON_STATUS_USED":        2,
		"COUPON_STATUS_EXPIRED":     3,
		"COUPON_STATUS_REVOKED":     4,
	}
)

func (x CouponStatus) Enum() *CouponStatus {
	p := new(CouponStatus)
	*p = x
	return p
}

func (x CouponStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouponStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coupons_proto_enumTypes[1].Descriptor()
}

func (CouponStatus) Type() protoreflect.EnumType {
	return &file_coupons_proto_enumTypes[1]
}

func (x CouponStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouponStatus.Descriptor instead.
func (CouponStatus) EnumDescriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{1}
}

// 优惠券信息
type Coupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 优惠券ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // 券名称
	Type           CouponType             `protobuf:"varint,3,opt,name=type,proto3,enum=coupons.CouponType" json:"type,omitempty"`                    // 类型：1-满减 2-折扣 3-立减
	Value          string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                                           // 优惠值（根据类型：分/百分比）
	MinAmount      string                 `protobuf:"bytes,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`                  // 最低消费金额（分）
	StartTime      string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                  // 有效期开始
	EndTime        string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                        // 有效期结束
	TotalCount     uint64                 `protobuf:"varint,9,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`              // 发行总量
	RemainingCount uint64                 `protobuf:"varint,10,opt,name=remaining_count,json=remainingCount,proto3" json:"remaining_count,omitempty"` // 剩余数量
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 创建时间
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_coupons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{0}
}

func (x *Coupon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Coupon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Coupon) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *Coupon) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Coupon) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *Coupon) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Coupon) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Coupon) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Coupon) GetRemainingCount() uint64 {
	if x != nil {
		return x.RemainingCount
	}
	return 0
}

func (x *Coupon) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Coupon) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 用户优惠券信息
type UserCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 用户优惠券ID
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID
	CouponId      string                 `protobuf:"bytes,3,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`        // 优惠券ID
	Status        CouponStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=coupons.CouponStatus" json:"status,omitempty"` // 状态：0-未使用 1-已使用 2-已过期
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`           // 订单完成指定的订单
	UsedAt        string                 `protobuf:"bytes,6,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`              // 使用时间
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`     // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_coupons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{1}
}

func (x *UserCoupon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *UserCoupon) GetStatus() CouponStatus {
	if x != nil {
		return x.Status
	}
	return CouponStatus_COUPON_STATUS_UNSPECIFIED
}

func (x *UserCoupon) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UserCoupon) GetUsedAt() string {
	if x != nil {
		return x.UsedAt
	}
	return ""
}

func (x *UserCoupon) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserCoupon) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 优惠券使用记录
type CouponUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                    // 使用记录ID
	PreOrderId     string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"` // 关联的订单ID
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CouponId       string                 `protobuf:"bytes,4,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`                                // 优惠券ID
	UserId         int32                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                     // 用户ID
	CouponType     CouponType             `protobuf:"varint,6,opt,name=coupon_type,json=couponType,proto3,enum=coupons.CouponType" json:"coupon_type,omitempty"` // 当时优惠券类型：1-满减 2-折扣 3-立减
	OriginValue    string                 `protobuf:"bytes,7,opt,name=origin_value,json=originValue,proto3" json:"origin_value,omitempty"`                       // 当时优惠值（根据类型：分/百分比）
	DiscountAmount string                 `protobuf:"bytes,8,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`              // 抵扣金额（分）
	AppliedAt      string                 `protobuf:"bytes,9,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`                             // 应用时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CouponUsage) Reset() {
	*x = CouponUsage{}
	mi := &file_coupons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponUsage) ProtoMessage() {}

func (x *CouponUsage) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponUsage.ProtoReflect.Descriptor instead.
func (*CouponUsage) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{2}
}

func (x *CouponUsage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponUsage) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *CouponUsage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CouponUsage) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *CouponUsage) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CouponUsage) GetCouponType() CouponType {
	if x != nil {
		return x.CouponType
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *CouponUsage) GetOriginValue() string {
	if x != nil {
		return x.OriginValue
	}
	return ""
}

func (x *CouponUsage) GetDiscountAmount() string {
	if x != nil {
		return x.DiscountAmount
	}
	return ""
}

func (x *CouponUsage) GetAppliedAt() string {
	if x != nil {
		return x.AppliedAt
	}
	return ""
}

// 分页请求
type PaginationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationReq) Reset() {
	*x = PaginationReq{}
	mi := &file_coupons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationReq) ProtoMessage() {}

func (x *PaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationReq.ProtoReflect.Descriptor instead.
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 获取优惠券列表请求
type ListCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationReq         `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 可选：优惠券类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsReq) Reset() {
	*x = ListCouponsReq{}
	mi := &file_coupons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsReq) ProtoMessage() {}

func (x *ListCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsReq.ProtoReflect.Descriptor instead.
func (*ListCouponsReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{4}
}

func (x *ListCouponsReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCouponsReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 获取优惠券列表响应
type ListCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Coupons       []*Coupon              `protobuf:"bytes,3,rep,name=coupons,proto3" json:"coupons,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsResp) Reset() {
	*x = ListCouponsResp{}
	mi := &file_coupons_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsResp) ProtoMessage() {}

func (x *ListCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsResp.ProtoReflect.Descriptor instead.
func (*ListCouponsResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{5}
}

func (x *ListCouponsResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListCouponsResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ListCouponsResp) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListCouponsResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取单个优惠券请求
type GetCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 优惠券ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponReq) Reset() {
	*x = GetCouponReq{}
	mi := &file_coupons_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponReq) ProtoMessage() {}

func (x *GetCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponReq.ProtoReflect.Descriptor instead.
func (*GetCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{6}
}

func (x *GetCouponReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取单个优惠券响应
type GetCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Coupon        *Coupon                `protobuf:"bytes,3,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponResp) Reset() {
	*x = GetCouponResp{}
	mi := &file_coupons_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponResp) ProtoMessage() {}

func (x *GetCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponResp.ProtoReflect.Descriptor instead.
func (*GetCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{7}
}

func (x *GetCouponResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetCouponResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetCouponResp) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// 获取用户优惠券列表请求
type ListUserCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Pagination    *PaginationReq         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsReq) Reset() {
	*x = ListUserCouponsReq{}
	mi := &file_coupons_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsReq) ProtoMessage() {}

func (x *ListUserCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsReq.ProtoReflect.Descriptor instead.
func (*ListUserCouponsReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserCouponsReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取用户优惠券列表响应
type ListUserCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	UserCoupons   []*UserCoupon          `protobuf:"bytes,3,rep,name=user_coupons,json=userCoupons,proto3" json:"user_coupons,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsResp) Reset() {
	*x = ListUserCouponsResp{}
	mi := &file_coupons_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsResp) ProtoMessage() {}

func (x *ListUserCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsResp.ProtoReflect.Descriptor instead.
func (*ListUserCouponsResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserCouponsResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListUserCouponsResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ListUserCouponsResp) GetUserCoupons() []*UserCoupon {
	if x != nil {
		return x.UserCoupons
	}
	return nil
}

func (x *ListUserCouponsResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 用户领取优惠券请求
type ClaimCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	CouponId      string                 `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 优惠券ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponReq) Reset() {
	*x = ClaimCouponReq{}
	mi := &file_coupons_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponReq) ProtoMessage() {}

func (x *ClaimCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponReq.ProtoReflect.Descriptor instead.
func (*ClaimCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

// 用户领取优惠券响应
type ClaimCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Coupon        *Coupon                `protobuf:"bytes,3,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponResp) Reset() {
	*x = ClaimCouponResp{}
	mi := &file_coupons_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResp) ProtoMessage() {}

func (x *ClaimCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResp.ProtoReflect.Descriptor instead.
func (*ClaimCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimCouponResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ClaimCouponResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ClaimCouponResp) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_coupons_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{12}
}

func (x *Items) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Items) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 计算优惠券请求
type CalculateCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	CouponId      string                 `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 优惠券ID
	Items         []*Items               `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateCouponReq) Reset() {
	*x = CalculateCouponReq{}
	mi := &file_coupons_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCouponReq) ProtoMessage() {}

func (x *CalculateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCouponReq.ProtoReflect.Descriptor instead.
func (*CalculateCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{13}
}

func (x *CalculateCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CalculateCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *CalculateCouponReq) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

// 计算优惠券响应
type CalculateCouponResp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg  string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// 金额相关
	OriginAmount   int64 `protobuf:"varint,3,opt,name=origin_amount,json=originAmount,proto3" json:"origin_amount,omitempty"`       // 原始订单金额（单位：分）
	FinalAmount    int64 `protobuf:"varint,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`          // 最终应付金额（分）
	DiscountAmount int64 `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"` // 总抵扣金额（分）
	// 优惠券信息
	CouponType     string `protobuf:"bytes,6,opt,name=coupon_type,json=couponType,proto3" json:"coupon_type,omitempty"`             // 优惠券类型（如 DISCOUNT/满减券）
	IsUsable       bool   `protobuf:"varint,7,opt,name=is_usable,json=isUsable,proto3" json:"is_usable,omitempty"`                  // 是否可用
	UnusableReason string `protobuf:"bytes,8,opt,name=unusable_reason,json=unusableReason,proto3" json:"unusable_reason,omitempty"` // 不可用原因（当 is_usable=false 时有效）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateCouponResp) Reset() {
	*x = CalculateCouponResp{}
	mi := &file_coupons_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateCouponResp) ProtoMessage() {}

func (x *CalculateCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateCouponResp.ProtoReflect.Descriptor instead.
func (*CalculateCouponResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{14}
}

func (x *CalculateCouponResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CalculateCouponResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CalculateCouponResp) GetOriginAmount() int64 {
	if x != nil {
		return x.OriginAmount
	}
	return 0
}

func (x *CalculateCouponResp) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *CalculateCouponResp) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CalculateCouponResp) GetCouponType() string {
	if x != nil {
		return x.CouponType
	}
	return ""
}

func (x *CalculateCouponResp) GetIsUsable() bool {
	if x != nil {
		return x.IsUsable
	}
	return false
}

func (x *CalculateCouponResp) GetUnusableReason() string {
	if x != nil {
		return x.UnusableReason
	}
	return ""
}

// 获取优惠券使用记录请求
type ListCouponUsagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *PaginationReq         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponUsagesReq) Reset() {
	*x = ListCouponUsagesReq{}
	mi := &file_coupons_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponUsagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponUsagesReq) ProtoMessage() {}

func (x *ListCouponUsagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponUsagesReq.ProtoReflect.Descriptor instead.
func (*ListCouponUsagesReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{15}
}

func (x *ListCouponUsagesReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListCouponUsagesReq) GetPagination() *PaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 获取优惠券使用记录响应
type ListCouponUsagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Usages        []*CouponUsage         `protobuf:"bytes,3,rep,name=usages,proto3" json:"usages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponUsagesResp) Reset() {
	*x = ListCouponUsagesResp{}
	mi := &file_coupons_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponUsagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponUsagesResp) ProtoMessage() {}

func (x *ListCouponUsagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponUsagesResp.ProtoReflect.Descriptor instead.
func (*ListCouponUsagesResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{16}
}

func (x *ListCouponUsagesResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListCouponUsagesResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ListCouponUsagesResp) GetUsages() []*CouponUsage {
	if x != nil {
		return x.Usages
	}
	return nil
}

func (x *ListCouponUsagesResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 请求/响应结构
type LockCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCouponId  string                 `protobuf:"bytes,2,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"` // 用户优惠券ID
	PreOrderId    string                 `protobuf:"bytes,3,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`       // 关联订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockCouponReq) Reset() {
	*x = LockCouponReq{}
	mi := &file_coupons_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCouponReq) ProtoMessage() {}

func (x *LockCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCouponReq.ProtoReflect.Descriptor instead.
func (*LockCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{17}
}

func (x *LockCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockCouponReq) GetUserCouponId() string {
	if x != nil {
		return x.UserCouponId
	}
	return ""
}

func (x *LockCouponReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

type UseCouponReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreOrderId     string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CouponId       string                 `protobuf:"bytes,4,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	OriginAmount   int64                  `protobuf:"varint,6,opt,name=origin_amount,json=originAmount,proto3" json:"origin_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	mi := &file_coupons_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{18}
}

func (x *UseCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseCouponReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *UseCouponReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UseCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *UseCouponReq) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *UseCouponReq) GetOriginAmount() int64 {
	if x != nil {
		return x.OriginAmount
	}
	return 0
}

type ReleaseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCouponId  string                 `protobuf:"bytes,1,opt,name=user_coupon_id,json=userCouponId,proto3" json:"user_coupon_id,omitempty"`
	PreOrderId    string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 释放原因（超时/用户取消）
	UserId        int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponReq) Reset() {
	*x = ReleaseCouponReq{}
	mi := &file_coupons_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponReq) ProtoMessage() {}

func (x *ReleaseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponReq.ProtoReflect.Descriptor instead.
func (*ReleaseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{19}
}

func (x *ReleaseCouponReq) GetUserCouponId() string {
	if x != nil {
		return x.UserCouponId
	}
	return ""
}

func (x *ReleaseCouponReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *ReleaseCouponReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReleaseCouponReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_coupons_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupons_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_coupons_proto_rawDescGZIP(), []int{20}
}

func (x *EmptyResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmptyResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_coupons_proto protoreflect.FileDescriptor

const file_coupons_proto_rawDesc = "" +
	"\n" +
	"\rcoupons.proto\x12\acoupons\"\xcc\x02\n" +
	"\x06Coupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.coupons.CouponTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_count\x18\t \x01(\x04R\n" +
	"totalCount\x12'\n" +
	"\x0fremaining_count\x18\n" +
	" \x01(\x04R\x0eremainingCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xf3\x01\n" +
	"\n" +
	"UserCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x03 \x01(\tR\bcouponId\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.coupons.CouponStatusR\x06status\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12\x17\n" +
	"\aused_at\x18\x06 \x01(\tR\x06usedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xb1\x02\n" +
	"\vCouponUsage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1b\n" +
	"\tcoupon_id\x18\x04 \x01(\tR\bcouponId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x05R\x06userId\x124\n" +
	"\vcoupon_type\x18\x06 \x01(\x0e2\x13.coupons.CouponTypeR\n" +
	"couponType\x12!\n" +
	"\forigin_value\x18\a \x01(\tR\voriginValue\x12'\n" +
	"\x0fdiscount_amount\x18\b \x01(\tR\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"applied_at\x18\t \x01(\tR\tappliedAt\"7\n" +
	"\rPaginationReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\\\n" +
	"\x0eListCouponsReq\x126\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x16.coupons.PaginationReqR\n" +
	"pagination\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"\x9d\x01\n" +
	"\x0fListCouponsResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12)\n" +
	"\acoupons\x18\x03 \x03(\v2\x0f.coupons.CouponR\acoupons\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\x1e\n" +
	"\fGetCouponReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\rGetCouponResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12'\n" +
	"\x06coupon\x18\x03 \x01(\v2\x0f.coupons.CouponR\x06coupon\"e\n" +
	"\x12ListUserCouponsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.coupons.PaginationReqR\n" +
	"pagination\"\xae\x01\n" +
	"\x13ListUserCouponsResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x126\n" +
	"\fuser_coupons\x18\x03 \x03(\v2\x13.coupons.UserCouponR\vuserCoupons\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"F\n" +
	"\x0eClaimCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\tR\bcouponId\"z\n" +
	"\x0fClaimCouponResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12'\n" +
	"\x06coupon\x18\x03 \x01(\v2\x0f.coupons.CouponR\x06coupon\"B\n" +
	"\x05Items\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"p\n" +
	"\x12CalculateCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\tR\bcouponId\x12$\n" +
	"\x05items\x18\x03 \x03(\v2\x0e.coupons.ItemsR\x05items\"\xad\x02\n" +
	"\x13CalculateCouponResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12#\n" +
	"\rorigin_amount\x18\x03 \x01(\x03R\foriginAmount\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x03R\vfinalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x03R\x0ediscountAmount\x12\x1f\n" +
	"\vcoupon_type\x18\x06 \x01(\tR\n" +
	"couponType\x12\x1b\n" +
	"\tis_usable\x18\a \x01(\bR\bisUsable\x12'\n" +
	"\x0funusable_reason\x18\b \x01(\tR\x0eunusableReason\"f\n" +
	"\x13ListCouponUsagesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.coupons.PaginationReqR\n" +
	"pagination\"\xa5\x01\n" +
	"\x14ListCouponUsagesResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12,\n" +
	"\x06usages\x18\x03 \x03(\v2\x14.coupons.CouponUsageR\x06usages\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"p\n" +
	"\rLockCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12$\n" +
	"\x0euser_coupon_id\x18\x02 \x01(\tR\fuserCouponId\x12 \n" +
	"\fpre_order_id\x18\x03 \x01(\tR\n" +
	"preOrderId\"\xcf\x01\n" +
	"\fUseCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1b\n" +
	"\tcoupon_id\x18\x04 \x01(\tR\bcouponId\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x03R\x0ediscountAmount\x12#\n" +
	"\rorigin_amount\x18\x06 \x01(\x03R\foriginAmount\"\x8b\x01\n" +
	"\x10ReleaseCouponReq\x12$\n" +
	"\x0euser_coupon_id\x18\x01 \x01(\tR\fuserCouponId\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\"K\n" +
	"\tEmptyResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg*\x81\x01\n" +
	"\n" +
	"CouponType\x12\x1b\n" +
	"\x17COUPON_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOUPON_TYPE_FULL_REDUCTION\x10\x01\x12\x18\n" +
	"\x14COUPON_TYPE_DISCOUNT\x10\x02\x12\x1c\n" +
	"\x18COUPON_TYPE_FIXED_AMOUNT\x10\x03*\x95\x01\n" +
	"\fCouponStatus\x12\x1d\n" +
	"\x19COUPON_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COUPON_STATUS_LOCKED\x10\x01\x12\x16\n" +
	"\x12COUPON_STATUS_USED\x10\x02\x12\x19\n" +
	"\x15COUPON_STATUS_EXPIRED\x10\x03\x12\x19\n" +
	"\x15COUPON_STATUS_REVOKED\x10\x042\xe8\x04\n" +
	"\aCoupons\x12@\n" +
	"\vListCoupons\x12\x17.coupons.ListCouponsReq\x1a\x18.coupons.ListCouponsResp\x12:\n" +
	"\tGetCoupon\x12\x15.coupons.GetCouponReq\x1a\x16.coupons.GetCouponResp\x12@\n" +
	"\vClaimCoupon\x12\x17.coupons.ClaimCouponReq\x1a\x18.coupons.ClaimCouponResp\x12L\n" +
	"\x0fListUserCoupons\x12\x1b.coupons.ListUserCouponsReq\x1a\x1c.coupons.ListUserCouponsResp\x12L\n" +
	"\x0fCalculateCoupon\x12\x1b.coupons.CalculateCouponReq\x1a\x1c.coupons.CalculateCouponResp\x12O\n" +
	"\x10ListCouponUsages\x12\x1c.coupons.ListCouponUsagesReq\x1a\x1d.coupons.ListCouponUsagesResp\x128\n" +
	"\n" +
	"LockCoupon\x12\x16.coupons.LockCouponReq\x1a\x12.coupons.EmptyResp\x12>\n" +
	"\rReleaseCoupon\x12\x19.coupons.ReleaseCouponReq\x1a\x12.coupons.EmptyResp\x126\n" +
	"\tUseCoupon\x12\x15.coupons.UseCouponReq\x1a\x12.coupons.EmptyRespB\vZ\t./couponsb\x06proto3"

var (
	file_coupons_proto_rawDescOnce sync.Once
	file_coupons_proto_rawDescData []byte
)

func file_coupons_proto_rawDescGZIP() []byte {
	file_coupons_proto_rawDescOnce.Do(func() {
		file_coupons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupons_proto_rawDesc), len(file_coupons_proto_rawDesc)))
	})
	return file_coupons_proto_rawDescData
}

var file_coupons_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coupons_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_coupons_proto_goTypes = []any{
	(CouponType)(0),              // 0: coupons.CouponType
	(CouponStatus)(0),            // 1: coupons.CouponStatus
	(*Coupon)(nil),               // 2: coupons.Coupon
	(*UserCoupon)(nil),           // 3: coupons.UserCoupon
	(*CouponUsage)(nil),          // 4: coupons.CouponUsage
	(*PaginationReq)(nil),        // 5: coupons.PaginationReq
	(*ListCouponsReq)(nil),       // 6: coupons.ListCouponsReq
	(*ListCouponsResp)(nil),      // 7: coupons.ListCouponsResp
	(*GetCouponReq)(nil),         // 8: coupons.GetCouponReq
	(*GetCouponResp)(nil),        // 9: coupons.GetCouponResp
	(*ListUserCouponsReq)(nil),   // 10: coupons.ListUserCouponsReq
	(*ListUserCouponsResp)(nil),  // 11: coupons.ListUserCouponsResp
	(*ClaimCouponReq)(nil),       // 12: coupons.ClaimCouponReq
	(*ClaimCouponResp)(nil),      // 13: coupons.ClaimCouponResp
	(*Items)(nil),                // 14: coupons.Items
	(*CalculateCouponReq)(nil),   // 15: coupons.CalculateCouponReq
	(*CalculateCouponResp)(nil),  // 16: coupons.CalculateCouponResp
	(*ListCouponUsagesReq)(nil),  // 17: coupons.ListCouponUsagesReq
	(*ListCouponUsagesResp)(nil), // 18: coupons.ListCouponUsagesResp
	(*LockCouponReq)(nil),        // 19: coupons.LockCouponReq
	(*UseCouponReq)(nil),         // 20: coupons.UseCouponReq
	(*ReleaseCouponReq)(nil),     // 21: coupons.ReleaseCouponReq
	(*EmptyResp)(nil),            // 22: coupons.EmptyResp
}
var file_coupons_proto_depIdxs = []int32{
	0,  // 0: coupons.Coupon.type:type_name -> coupons.CouponType
	1,  // 1: coupons.UserCoupon.status:type_name -> coupons.CouponStatus
	0,  // 2: coupons.CouponUsage.coupon_type:type_name -> coupons.CouponType
	5,  // 3: coupons.ListCouponsReq.pagination:type_name -> coupons.PaginationReq
	2,  // 4: coupons.ListCouponsResp.coupons:type_name -> coupons.Coupon
	2,  // 5: coupons.GetCouponResp.coupon:type_name -> coupons.Coupon
	5,  // 6: coupons.ListUserCouponsReq.pagination:type_name -> coupons.PaginationReq
	3,  // 7: coupons.ListUserCouponsResp.user_coupons:type_name -> coupons.UserCoupon
	2,  // 8: coupons.ClaimCouponResp.coupon:type_name -> coupons.Coupon
	14, // 9: coupons.CalculateCouponReq.items:type_name -> coupons.Items
	5,  // 10: coupons.ListCouponUsagesReq.pagination:type_name -> coupons.PaginationReq
	4,  // 11: coupons.ListCouponUsagesResp.usages:type_name -> coupons.CouponUsage
	6,  // 12: coupons.Coupons.ListCoupons:input_type -> coupons.ListCouponsReq
	8,  // 13: coupons.Coupons.GetCoupon:input_type -> coupons.GetCouponReq
	12, // 14: coupons.Coupons.ClaimCoupon:input_type -> coupons.ClaimCouponReq
	10, // 15: coupons.Coupons.ListUserCoupons:input_type -> coupons.ListUserCouponsReq
	15, // 16: coupons.Coupons.CalculateCoupon:input_type -> coupons.CalculateCouponReq
	17, // 17: coupons.Coupons.ListCouponUsages:input_type -> coupons.ListCouponUsagesReq
	19, // 18: coupons.Coupons.LockCoupon:input_type -> coupons.LockCouponReq
	21, // 19: coupons.Coupons.ReleaseCoupon:input_type -> coupons.ReleaseCouponReq
	20, // 20: coupons.Coupons.UseCoupon:input_type -> coupons.UseCouponReq
	7,  // 21: coupons.Coupons.ListCoupons:output_type -> coupons.ListCouponsResp
	9,  // 22: coupons.Coupons.GetCoupon:output_type -> coupons.GetCouponResp
	13, // 23: coupons.Coupons.ClaimCoupon:output_type -> coupons.ClaimCouponResp
	11, // 24: coupons.Coupons.ListUserCoupons:output_type -> coupons.ListUserCouponsResp
	16, // 25: coupons.Coupons.CalculateCoupon:output_type -> coupons.CalculateCouponResp
	18, // 26: coupons.Coupons.ListCouponUsages:output_type -> coupons.ListCouponUsagesResp
	22, // 27: coupons.Coupons.LockCoupon:output_type -> coupons.EmptyResp
	22, // 28: coupons.Coupons.ReleaseCoupon:output_type -> coupons.EmptyResp
	22, // 29: coupons.Coupons.UseCoupon:output_type -> coupons.EmptyResp
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_coupons_proto_init() }
func file_coupons_proto_init() {
	if File_coupons_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupons_proto_rawDesc), len(file_coupons_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupons_proto_goTypes,
		DependencyIndexes: file_coupons_proto_depIdxs,
		EnumInfos:         file_coupons_proto_enumTypes,
		MessageInfos:      file_coupons_proto_msgTypes,
	}.Build()
	File_coupons_proto = out.File
	file_coupons_proto_goTypes = nil
	file_coupons_proto_depIdxs = nil
}
