// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: checkout.proto

package checkout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态枚举
type CheckoutStatus int32

const (
	CheckoutStatus_RESERVING CheckoutStatus = 0 // 预占中
	CheckoutStatus_CONFIRMED CheckoutStatus = 1 // 已确认
	CheckoutStatus_CANCELLED CheckoutStatus = 2 // 已取消
	CheckoutStatus_EXPIRED   CheckoutStatus = 3 // 已过期
)

// Enum value maps for CheckoutStatus.
var (
	CheckoutStatus_name = map[int32]string{
		0: "RESERVING",
		1: "CONFIRMED",
		2: "CANCELLED",
		3: "EXPIRED",
	}
	CheckoutStatus_value = map[string]int32{
		"RESERVING": 0,
		"CONFIRMED": 1,
		"CANCELLED": 2,
		"EXPIRED":   3,
	}
)

func (x CheckoutStatus) Enum() *CheckoutStatus {
	p := new(CheckoutStatus)
	*p = x
	return p
}

func (x CheckoutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckoutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_checkout_proto_enumTypes[0].Descriptor()
}

func (CheckoutStatus) Type() protoreflect.EnumType {
	return &file_checkout_proto_enumTypes[0]
}

func (x CheckoutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckoutStatus.Descriptor instead.
func (CheckoutStatus) EnumDescriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

type CheckoutItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductDesc   string                 `protobuf:"bytes,4,opt,name=product_desc,json=productDesc,proto3" json:"product_desc,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"` // 单位：分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutItem) Reset() {
	*x = CheckoutItem{}
	mi := &file_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutItem) ProtoMessage() {}

func (x *CheckoutItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutItem.ProtoReflect.Descriptor instead.
func (*CheckoutItem) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutItem) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckoutItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CheckoutItem) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *CheckoutItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CheckoutOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PreOrderId     string                 `protobuf:"bytes,1,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`   // 预订单ID
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	Status         CheckoutStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=checkout.CheckoutStatus" json:"status,omitempty"` // 订单状态
	ExpireTime     int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`    // 过期时间戳)秒）
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Items          []*CheckoutItem        `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"` // 商品明细快照
	OriginalAmount int64                  `protobuf:"varint,8,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	FinalAmount    int64                  `protobuf:"varint,9,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckoutOrder) Reset() {
	*x = CheckoutOrder{}
	mi := &file_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutOrder) ProtoMessage() {}

func (x *CheckoutOrder) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutOrder.ProtoReflect.Descriptor instead.
func (*CheckoutOrder) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutOrder) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *CheckoutOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutOrder) GetStatus() CheckoutStatus {
	if x != nil {
		return x.Status
	}
	return CheckoutStatus_RESERVING
}

func (x *CheckoutOrder) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CheckoutOrder) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CheckoutOrder) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CheckoutOrder) GetItems() []*CheckoutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckoutOrder) GetOriginalAmount() int64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *CheckoutOrder) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

type CheckoutDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreOrderId    string                 `protobuf:"bytes,1,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutDetailReq) Reset() {
	*x = CheckoutDetailReq{}
	mi := &file_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutDetailReq) ProtoMessage() {}

func (x *CheckoutDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutDetailReq.ProtoReflect.Descriptor instead.
func (*CheckoutDetailReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutDetailReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *CheckoutDetailReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateCheckoutStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreOrderId    string                 `protobuf:"bytes,1,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        CheckoutStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=checkout.CheckoutStatus" json:"status,omitempty"` // 状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCheckoutStatusReq) Reset() {
	*x = UpdateCheckoutStatusReq{}
	mi := &file_checkout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCheckoutStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCheckoutStatusReq) ProtoMessage() {}

func (x *UpdateCheckoutStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCheckoutStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateCheckoutStatusReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCheckoutStatusReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *UpdateCheckoutStatusReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCheckoutStatusReq) GetStatus() CheckoutStatus {
	if x != nil {
		return x.Status
	}
	return CheckoutStatus_RESERVING
}

type CheckoutListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 从1开始计数
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 业务层校验最大值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutListReq) Reset() {
	*x = CheckoutListReq{}
	mi := &file_checkout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutListReq) ProtoMessage() {}

func (x *CheckoutListReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutListReq.ProtoReflect.Descriptor instead.
func (*CheckoutListReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{4}
}

func (x *CheckoutListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CheckoutListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CheckoutReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        uint32                   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponId      string                   `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`       //
	OrderItems    []*CheckoutReq_OrderItem `protobuf:"bytes,3,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"` // 新增：直接传商品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutReq) Reset() {
	*x = CheckoutReq{}
	mi := &file_checkout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReq) ProtoMessage() {}

func (x *CheckoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReq.ProtoReflect.Descriptor instead.
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{5}
}

func (x *CheckoutReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *CheckoutReq) GetOrderItems() []*CheckoutReq_OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

// 分页响应结构
type CheckoutListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CheckoutOrder       `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"` // 订单数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutListResp) Reset() {
	*x = CheckoutListResp{}
	mi := &file_checkout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutListResp) ProtoMessage() {}

func (x *CheckoutListResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutListResp.ProtoReflect.Descriptor instead.
func (*CheckoutListResp) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{6}
}

func (x *CheckoutListResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckoutListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CheckoutListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CheckoutListResp) GetData() []*CheckoutOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`     // 预占库存有效期)如30分钟）
	PreOrderId    string                 `protobuf:"bytes,4,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`    // 结算令牌)用于后续提交）也就是pre_order_id)幂等控制）
	PayMethod     []int64                `protobuf:"varint,5,rep,packed,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"` // 支付方式 )如：微信支付：1、支付宝支付：2）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResp) Reset() {
	*x = CheckoutResp{}
	mi := &file_checkout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResp) ProtoMessage() {}

func (x *CheckoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResp.ProtoReflect.Descriptor instead.
func (*CheckoutResp) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckoutResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CheckoutResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CheckoutResp) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *CheckoutResp) GetPayMethod() []int64 {
	if x != nil {
		return x.PayMethod
	}
	return nil
}

type CheckoutDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Data          *CheckoutOrder         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutDetailResp) Reset() {
	*x = CheckoutDetailResp{}
	mi := &file_checkout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutDetailResp) ProtoMessage() {}

func (x *CheckoutDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutDetailResp.ProtoReflect.Descriptor instead.
func (*CheckoutDetailResp) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{8}
}

func (x *CheckoutDetailResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckoutDetailResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CheckoutDetailResp) GetData() *CheckoutOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReleaseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreOrderId    string                 `protobuf:"bytes,1,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReq) Reset() {
	*x = ReleaseReq{}
	mi := &file_checkout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReq) ProtoMessage() {}

func (x *ReleaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReq.ProtoReflect.Descriptor instead.
func (*ReleaseReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *ReleaseReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_checkout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{10}
}

func (x *EmptyResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmptyResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreOrderId    string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	mi := &file_checkout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStatusReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateStatusReq) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

type CheckoutReq_OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutReq_OrderItem) Reset() {
	*x = CheckoutReq_OrderItem{}
	mi := &file_checkout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutReq_OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReq_OrderItem) ProtoMessage() {}

func (x *CheckoutReq_OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReq_OrderItem.ProtoReflect.Descriptor instead.
func (*CheckoutReq_OrderItem) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CheckoutReq_OrderItem) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckoutReq_OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_checkout_proto protoreflect.FileDescriptor

const file_checkout_proto_rawDesc = "" +
	"\n" +
	"\x0echeckout.proto\x12\bcheckout\"\xa5\x01\n" +
	"\fCheckoutItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_desc\x18\x04 \x01(\tR\vproductDesc\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\"\xd5\x02\n" +
	"\rCheckoutOrder\x12 \n" +
	"\fpre_order_id\x18\x01 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.checkout.CheckoutStatusR\x06status\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12,\n" +
	"\x05items\x18\a \x03(\v2\x16.checkout.CheckoutItemR\x05items\x12'\n" +
	"\x0foriginal_amount\x18\b \x01(\x03R\x0eoriginalAmount\x12!\n" +
	"\ffinal_amount\x18\t \x01(\x03R\vfinalAmount\"N\n" +
	"\x11CheckoutDetailReq\x12 \n" +
	"\fpre_order_id\x18\x01 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\x86\x01\n" +
	"\x17UpdateCheckoutStatusReq\x12 \n" +
	"\fpre_order_id\x18\x01 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.checkout.CheckoutStatusR\x06status\"[\n" +
	"\x0fCheckoutListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcd\x01\n" +
	"\vCheckoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\tR\bcouponId\x12@\n" +
	"\vorder_items\x18\x03 \x03(\v2\x1f.checkout.CheckoutReq.OrderItemR\n" +
	"orderItems\x1aF\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x95\x01\n" +
	"\x10CheckoutListResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12+\n" +
	"\x04data\x18\x04 \x03(\v2\x17.checkout.CheckoutOrderR\x04data\"\xb0\x01\n" +
	"\fCheckoutResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x03R\n" +
	"expireTime\x12 \n" +
	"\fpre_order_id\x18\x04 \x01(\tR\n" +
	"preOrderId\x12\x1d\n" +
	"\n" +
	"pay_method\x18\x05 \x03(\x03R\tpayMethod\"\x81\x01\n" +
	"\x12CheckoutDetailResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.checkout.CheckoutOrderR\x04data\"G\n" +
	"\n" +
	"ReleaseReq\x12 \n" +
	"\fpre_order_id\x18\x01 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"K\n" +
	"\tEmptyResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"L\n" +
	"\x0fUpdateStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId*J\n" +
	"\x0eCheckoutStatus\x12\r\n" +
	"\tRESERVING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x032\xbf\x03\n" +
	"\x0fCheckoutService\x12@\n" +
	"\x0fPrepareCheckout\x12\x15.checkout.CheckoutReq\x1a\x16.checkout.CheckoutResp\x12<\n" +
	"\x0fReleaseCheckout\x12\x14.checkout.ReleaseReq\x1a\x13.checkout.EmptyResp\x12H\n" +
	"\x0fGetCheckoutList\x12\x19.checkout.CheckoutListReq\x1a\x1a.checkout.CheckoutListResp\x12N\n" +
	"\x11GetCheckoutDetail\x12\x1b.checkout.CheckoutDetailReq\x1a\x1c.checkout.CheckoutDetailResp\x12D\n" +
	"\x12UpdateStatus2Order\x12\x19.checkout.UpdateStatusReq\x1a\x13.checkout.EmptyResp\x12L\n" +
	"\x1aUpdateStatus2OrderRollback\x12\x19.checkout.UpdateStatusReq\x1a\x13.checkout.EmptyRespB\fZ\n" +
	"./checkoutb\x06proto3"

var (
	file_checkout_proto_rawDescOnce sync.Once
	file_checkout_proto_rawDescData []byte
)

func file_checkout_proto_rawDescGZIP() []byte {
	file_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)))
	})
	return file_checkout_proto_rawDescData
}

var file_checkout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_checkout_proto_goTypes = []any{
	(CheckoutStatus)(0),             // 0: checkout.CheckoutStatus
	(*CheckoutItem)(nil),            // 1: checkout.CheckoutItem
	(*CheckoutOrder)(nil),           // 2: checkout.CheckoutOrder
	(*CheckoutDetailReq)(nil),       // 3: checkout.CheckoutDetailReq
	(*UpdateCheckoutStatusReq)(nil), // 4: checkout.UpdateCheckoutStatusReq
	(*CheckoutListReq)(nil),         // 5: checkout.CheckoutListReq
	(*CheckoutReq)(nil),             // 6: checkout.CheckoutReq
	(*CheckoutListResp)(nil),        // 7: checkout.CheckoutListResp
	(*CheckoutResp)(nil),            // 8: checkout.CheckoutResp
	(*CheckoutDetailResp)(nil),      // 9: checkout.CheckoutDetailResp
	(*ReleaseReq)(nil),              // 10: checkout.ReleaseReq
	(*EmptyResp)(nil),               // 11: checkout.EmptyResp
	(*UpdateStatusReq)(nil),         // 12: checkout.UpdateStatusReq
	(*CheckoutReq_OrderItem)(nil),   // 13: checkout.CheckoutReq.OrderItem
}
var file_checkout_proto_depIdxs = []int32{
	0,  // 0: checkout.CheckoutOrder.status:type_name -> checkout.CheckoutStatus
	1,  // 1: checkout.CheckoutOrder.items:type_name -> checkout.CheckoutItem
	0,  // 2: checkout.UpdateCheckoutStatusReq.status:type_name -> checkout.CheckoutStatus
	13, // 3: checkout.CheckoutReq.order_items:type_name -> checkout.CheckoutReq.OrderItem
	2,  // 4: checkout.CheckoutListResp.data:type_name -> checkout.CheckoutOrder
	2,  // 5: checkout.CheckoutDetailResp.data:type_name -> checkout.CheckoutOrder
	6,  // 6: checkout.CheckoutService.PrepareCheckout:input_type -> checkout.CheckoutReq
	10, // 7: checkout.CheckoutService.ReleaseCheckout:input_type -> checkout.ReleaseReq
	5,  // 8: checkout.CheckoutService.GetCheckoutList:input_type -> checkout.CheckoutListReq
	3,  // 9: checkout.CheckoutService.GetCheckoutDetail:input_type -> checkout.CheckoutDetailReq
	12, // 10: checkout.CheckoutService.UpdateStatus2Order:input_type -> checkout.UpdateStatusReq
	12, // 11: checkout.CheckoutService.UpdateStatus2OrderRollback:input_type -> checkout.UpdateStatusReq
	8,  // 12: checkout.CheckoutService.PrepareCheckout:output_type -> checkout.CheckoutResp
	11, // 13: checkout.CheckoutService.ReleaseCheckout:output_type -> checkout.EmptyResp
	7,  // 14: checkout.CheckoutService.GetCheckoutList:output_type -> checkout.CheckoutListResp
	9,  // 15: checkout.CheckoutService.GetCheckoutDetail:output_type -> checkout.CheckoutDetailResp
	11, // 16: checkout.CheckoutService.UpdateStatus2Order:output_type -> checkout.EmptyResp
	11, // 17: checkout.CheckoutService.UpdateStatus2OrderRollback:output_type -> checkout.EmptyResp
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_checkout_proto_init() }
func file_checkout_proto_init() {
	if File_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_proto_depIdxs,
		EnumInfos:         file_checkout_proto_enumTypes,
		MessageInfos:      file_checkout_proto_msgTypes,
	}.Build()
	File_checkout_proto = out.File
	file_checkout_proto_goTypes = nil
	file_checkout_proto_depIdxs = nil
}
