Name: inventory.rpc
ListenOn: 0.0.0.0:10011
Mode: dev

# 服务发现
Consul:
  Host: localhost:8500
  Key: inventory.rpc
  Meta:
    Protocol: grpc

Telemetry:
  Name: inventory.rpc
  Endpoint: http://localhost:14268/api/traces
  Batcher: jaeger
  Sampler: 1.0


# 指标监控配置
DevServer:
  Enabled: true
  Host: localhost
  Port: 11011
  EnablePprof: false

Log:
  ServiceName: inventory-rpc
  Mode: console
  Encoding: json
  Path: ./logs/inventory-rpc

MysqlConfig:
  datasource: "root:root@tcp(localhost:33061)/mall?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai&time_zone=%27%2B08%3A00%27"

RedisConf:
  Host: localhost:6379
  Pass: leventsg
  Tls: false

KafkaMQ:
  Brokers:
    - "localhost:9092"
  Username: ""
  Password: ""
  Topics:
    CancelOrders:
      Topic: "cancel-orders"
      Group: "inventory-cancel-order-consumer"
      Offset: first
      Conns: 1
      Consumers: 1
      Processors: 2
      MinBytes: 10240
      MaxBytes: 10485760
      ForceCommit: false
    TimeoutOrders:
      Topic: "timeout-orders"
      Group: "inventory-timeout-order-consumer"
      Offset: first
      Conns: 1
      Consumers: 1
      Processors: 2
      MinBytes: 10240
      MaxBytes: 10485760
      ForceCommit: false
    CheckoutTimeouts:
      Topic: "checkout-timeouts"
      Group: "inventory-checkout-timeout-consumer"
      Offset: first
      Conns: 1
      Consumers: 1
      Processors: 2
      MinBytes: 10240
      MaxBytes: 10485760
      ForceCommit: false
    PaymentSuccesses:
      Topic: "payment-successes"
      Group: "inventory-payment-success-consumer"
      Offset: first
      Conns: 1
      Consumers: 1
      Processors: 2
      MinBytes: 10240
      MaxBytes: 10485760
      ForceCommit: false
