// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/leventsg/e-commerce-AI-system/apis/checkout/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WithClientMiddleware, serverCtx.WrapperAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/prepare",
					Handler: CheckoutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/checkout"),
	)
}
