// Code generated by goctl. DO NOT EDIT.
package types

type PaymentItem struct {
	PaymentID     string `json:"payment_id"`
	OrderID       string `json:"order_id"`
	PaidAmount    int64  `json:"paid_amount"`
	PaymentMethod int32  `json:"payment_method"`
	TransactionID string `json:"transaction_id"`
	PayURL        string `json:"pay_url"`
	Status        int32  `json:"status"`
	CreatedAt     int64  `json:"created_at"`
}

type PaymentListReq struct {
	PaymentMethod int32 `json:"method,optional"`
	Page          int32 `json:"page,default=1"`       // 页码（默认1）
	PageSize      int32 `json:"page_size,default=10"` // 页大小（默认10）
}

type PaymentListResponse struct {
	Data []PaymentItem `json:"data"`
}

type PaymentReq struct {
	OrderID       string `json:"order_id"`
	PaymentMethod int32  `json:"payment_method,options=1|2"`
}

type PaymentResponse struct {
	Data PaymentItem `json:"data"`
}
