// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.5

package user_address

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressesFieldNames          = builder.RawFieldNames(&UserAddresses{})
	userAddressesRows                = strings.Join(userAddressesFieldNames, ",")
	userAddressesRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressesFieldNames, "`address_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAddressesRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressesFieldNames, "`address_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserAddressesAddressIdPrefix = "cache:userAddresses:addressId:"
)

type (
	userAddressesModel interface {
		Insert(ctx context.Context, data *UserAddresses) (sql.Result, error)
		FindOne(ctx context.Context, addressId int64) (*UserAddresses, error)
		Update(ctx context.Context, data *UserAddresses) error
		Delete(ctx context.Context, addressId int64) error
	}

	defaultUserAddressesModel struct {
		sqlc.CachedConn
		table string
	}

	UserAddresses struct {
		AddressId       int64          `db:"address_id"`       // 主键，自增，地址ID
		UserId          int64          `db:"user_id"`          // 外键，关联到users表的user_id
		DetailedAddress string         `db:"detailed_address"` // 详细地址
		City            string         `db:"city"`             // 城市
		Province        sql.NullString `db:"province"`         // 州/省
		IsDefault       bool           `db:"is_default"`       // 是否默认地址
		RecipientName   string         `db:"recipient_name"`   // 收件人姓名
		PhoneNumber     sql.NullString `db:"phone_number"`     // 联系电话
		CreatedAt       time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newUserAddressesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAddressesModel {
	return &defaultUserAddressesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_addresses`",
	}
}

func (m *defaultUserAddressesModel) Delete(ctx context.Context, addressId int64) error {
	userAddressesAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressesAddressIdPrefix, addressId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `address_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, addressId)
	}, userAddressesAddressIdKey)
	return err
}

func (m *defaultUserAddressesModel) FindOne(ctx context.Context, addressId int64) (*UserAddresses, error) {
	userAddressesAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressesAddressIdPrefix, addressId)
	var resp UserAddresses
	err := m.QueryRowCtx(ctx, &resp, userAddressesAddressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `address_id` = ? limit 1", userAddressesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, addressId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) Insert(ctx context.Context, data *UserAddresses) (sql.Result, error) {
	userAddressesAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressesAddressIdPrefix, data.AddressId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userAddressesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.DetailedAddress, data.City, data.Province, data.IsDefault, data.RecipientName, data.PhoneNumber)
	}, userAddressesAddressIdKey)
	return ret, err
}

func (m *defaultUserAddressesModel) Update(ctx context.Context, data *UserAddresses) error {
	userAddressesAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressesAddressIdPrefix, data.AddressId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `address_id` = ?", m.table, userAddressesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.DetailedAddress, data.City, data.Province, data.IsDefault, data.RecipientName, data.PhoneNumber, data.AddressId)
	},
		userAddressesAddressIdKey,
		userAddressDetailCacheKey(data.UserId, data.AddressId),
		userAddressExistsCacheKey(data.UserId, data.AddressId),
	)
	return err
}

func (m *defaultUserAddressesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserAddressesAddressIdPrefix, primary)
}

func (m *defaultUserAddressesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `address_id` = ? limit 1", userAddressesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAddressesModel) tableName() string {
	return m.table
}
