// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package messages

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiMessagesFieldNames          = builder.RawFieldNames(&AiMessages{})
	aiMessagesRows                = strings.Join(aiMessagesFieldNames, ",")
	aiMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(aiMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(aiMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiMessagesIdPrefix                          = "cache:aiMessages:id:"
	cacheAiMessagesMsgIdPrefix                       = "cache:aiMessages:msgId:"
	cacheAiMessagesUserIdDedupeClientMessageIdPrefix = "cache:aiMessages:userId:dedupeClientMessageId:"
)

type (
	aiMessagesModel interface {
		Insert(ctx context.Context, data *AiMessages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AiMessages, error)
		FindOneByMsgId(ctx context.Context, msgId string) (*AiMessages, error)
		FindOneByUserIdDedupeClientMessageId(ctx context.Context, userId uint64, dedupeClientMessageId sql.NullString) (*AiMessages, error)
		Update(ctx context.Context, data *AiMessages) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAiMessagesModel struct {
		sqlc.CachedConn
		table string
	}

	AiMessages struct {
		Id                    uint64         `db:"id"`                       // 消息自增序号
		MsgId                 string         `db:"msg_id"`                   // 消息ID
		ConversationId        string         `db:"conversation_id"`          // 会话ID
		UserId                uint64         `db:"user_id"`                  // 用户ID
		Role                  string         `db:"role"`                     // user/assistant/tool
		Content               string         `db:"content"`                  // 消息内容
		Metadata              sql.NullString `db:"metadata"`                 // 扩展信息
		ClientMessageId       sql.NullString `db:"client_message_id"`        // 前端生成的用户消息幂等ID
		DedupeClientMessageId sql.NullString `db:"dedupe_client_message_id"` // 仅用户消息参与幂等唯一约束
		CreatedAt             time.Time      `db:"created_at"`
	}
)

func newAiMessagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAiMessagesModel {
	return &defaultAiMessagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ai_messages`",
	}
}

func (m *defaultAiMessagesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aiMessagesMsgIdKey := fmt.Sprintf("%s%v", cacheAiMessagesMsgIdPrefix, data.MsgId)
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, id)
	aiMessagesUserIdDedupeClientMessageIdKey := fmt.Sprintf("%s%v:%v", cacheAiMessagesUserIdDedupeClientMessageIdPrefix, data.UserId, data.DedupeClientMessageId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiMessagesMsgIdKey, aiMessagesIdKey, aiMessagesUserIdDedupeClientMessageIdKey)
	return err
}

func (m *defaultAiMessagesModel) FindOne(ctx context.Context, id uint64) (*AiMessages, error) {
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, id)
	var resp AiMessages
	err := m.QueryRowCtx(ctx, &resp, aiMessagesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiMessagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMessagesModel) FindOneByMsgId(ctx context.Context, msgId string) (*AiMessages, error) {
	aiMessagesMsgIdKey := fmt.Sprintf("%s%v", cacheAiMessagesMsgIdPrefix, msgId)
	var resp AiMessages
	err := m.QueryRowIndexCtx(ctx, &resp, aiMessagesMsgIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `msg_id` = ? limit 1", aiMessagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, msgId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMessagesModel) FindOneByUserIdDedupeClientMessageId(ctx context.Context, userId uint64, dedupeClientMessageId sql.NullString) (*AiMessages, error) {
	aiMessagesUserIdDedupeClientMessageIdKey := fmt.Sprintf("%s%v:%v", cacheAiMessagesUserIdDedupeClientMessageIdPrefix, userId, dedupeClientMessageId)
	var resp AiMessages
	err := m.QueryRowIndexCtx(ctx, &resp, aiMessagesUserIdDedupeClientMessageIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `dedupe_client_message_id` = ? limit 1", aiMessagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, dedupeClientMessageId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMessagesModel) Insert(ctx context.Context, data *AiMessages) (sql.Result, error) {
	aiMessagesMsgIdKey := fmt.Sprintf("%s%v", cacheAiMessagesMsgIdPrefix, data.MsgId)
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, data.Id)
	aiMessagesUserIdDedupeClientMessageIdKey := fmt.Sprintf("%s%v:%v", cacheAiMessagesUserIdDedupeClientMessageIdPrefix, data.UserId, data.DedupeClientMessageId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, aiMessagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MsgId, data.ConversationId, data.UserId, data.Role, data.Content, data.Metadata, data.ClientMessageId, data.DedupeClientMessageId)
	}, aiMessagesMsgIdKey, aiMessagesIdKey, aiMessagesUserIdDedupeClientMessageIdKey)
	return ret, err
}

func (m *defaultAiMessagesModel) Update(ctx context.Context, newData *AiMessages) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aiMessagesMsgIdKey := fmt.Sprintf("%s%v", cacheAiMessagesMsgIdPrefix, data.MsgId)
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, data.Id)
	aiMessagesUserIdDedupeClientMessageIdKey := fmt.Sprintf("%s%v:%v", cacheAiMessagesUserIdDedupeClientMessageIdPrefix, data.UserId, data.DedupeClientMessageId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiMessagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MsgId, newData.ConversationId, newData.UserId, newData.Role, newData.Content, newData.Metadata, newData.ClientMessageId, newData.DedupeClientMessageId, newData.Id)
	}, aiMessagesMsgIdKey, aiMessagesIdKey, aiMessagesUserIdDedupeClientMessageIdKey)
	return err
}

func (m *defaultAiMessagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, primary)
}

func (m *defaultAiMessagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiMessagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAiMessagesModel) tableName() string {
	return m.table
}
