// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package messages

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiMessagesFieldNames          = builder.RawFieldNames(&AiMessages{})
	aiMessagesRows                = strings.Join(aiMessagesFieldNames, ",")
	aiMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(aiMessagesFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(aiMessagesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiMessagesIdPrefix = "cache:aiMessages:id:"
)

type (
	aiMessagesModel interface {
		Insert(ctx context.Context, data *AiMessages) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AiMessages, error)
		Update(ctx context.Context, data *AiMessages) error
		Delete(ctx context.Context, id string) error
	}

	defaultAiMessagesModel struct {
		sqlc.CachedConn
		table string
	}

	AiMessages struct {
		Id             string         `db:"id"`              // 消息ID
		ConversationId string         `db:"conversation_id"` // 会话ID
		UserId         uint64         `db:"user_id"`         // 用户ID
		Role           string         `db:"role"`            // user/assistant/tool
		Content        string         `db:"content"`         // 消息内容
		Metadata       sql.NullString `db:"metadata"`        // 扩展信息
		CreatedAt      time.Time      `db:"created_at"`
	}
)

func newAiMessagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAiMessagesModel {
	return &defaultAiMessagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ai_messages`",
	}
}

func (m *defaultAiMessagesModel) Delete(ctx context.Context, id string) error {
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiMessagesIdKey)
	return err
}

func (m *defaultAiMessagesModel) FindOne(ctx context.Context, id string) (*AiMessages, error) {
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, id)
	var resp AiMessages
	err := m.QueryRowCtx(ctx, &resp, aiMessagesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiMessagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMessagesModel) Insert(ctx context.Context, data *AiMessages) (sql.Result, error) {
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, aiMessagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ConversationId, data.UserId, data.Role, data.Content, data.Metadata)
	}, aiMessagesIdKey)
	return ret, err
}

func (m *defaultAiMessagesModel) Update(ctx context.Context, data *AiMessages) error {
	aiMessagesIdKey := fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiMessagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ConversationId, data.UserId, data.Role, data.Content, data.Metadata, data.Id)
	}, aiMessagesIdKey)
	return err
}

func (m *defaultAiMessagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiMessagesIdPrefix, primary)
}

func (m *defaultAiMessagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiMessagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAiMessagesModel) tableName() string {
	return m.table
}
