// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/leventsg/e-commerce-AI-system/apis/payment/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WithClientMiddleware, serverCtx.WrapperAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: createPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: listPaymentsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/payment"),
	)
}
