// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: aiagent.proto

package server

import (
	"context"

	"github.com/leventsg/e-commerce-AI-system/services/aiagent/aiagent"
	"github.com/leventsg/e-commerce-AI-system/services/aiagent/internal/logic"
	"github.com/leventsg/e-commerce-AI-system/services/aiagent/internal/svc"
)

type AiAgentServer struct {
	svcCtx *svc.ServiceContext
	aiagent.UnimplementedAiAgentServer
}

func NewAiAgentServer(svcCtx *svc.ServiceContext) *AiAgentServer {
	return &AiAgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AiAgentServer) Chat(ctx context.Context, in *aiagent.ChatRequest) (*aiagent.ChatResponse, error) {
	l := logic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

func (s *AiAgentServer) ConfirmAction(ctx context.Context, in *aiagent.ConfirmActionRequest) (*aiagent.ConfirmActionResponse, error) {
	l := logic.NewConfirmActionLogic(ctx, s.svcCtx)
	return l.ConfirmAction(in)
}
