// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: aiagent.proto

package server

import (
	"context"

	"github.com/leventsg/e-commerce-AI-system/services/aiagent/aiagent"
	"github.com/leventsg/e-commerce-AI-system/services/aiagent/internal/logic"
	"github.com/leventsg/e-commerce-AI-system/services/aiagent/internal/svc"
)

type AiAgentServer struct {
	svcCtx *svc.ServiceContext
	aiagent.UnimplementedAiAgentServer
}

func NewAiAgentServer(svcCtx *svc.ServiceContext) *AiAgentServer {
	return &AiAgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AiAgentServer) Chat(in *aiagent.ChatRequest, stream aiagent.AiAgent_ChatServer) error {
	l := logic.NewChatLogic(stream.Context(), s.svcCtx)
	return l.Chat(in, stream)
}

func (s *AiAgentServer) ConfirmAction(in *aiagent.ConfirmActionRequest, stream aiagent.AiAgent_ConfirmActionServer) error {
	l := logic.NewConfirmActionLogic(stream.Context(), s.svcCtx)
	return l.ConfirmAction(in, stream)
}

func (s *AiAgentServer) ListConversations(ctx context.Context, in *aiagent.ListConversationsRequest) (*aiagent.ListConversationsResponse, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *AiAgentServer) ListMessages(ctx context.Context, in *aiagent.ListMessagesRequest) (*aiagent.ListMessagesResponse, error) {
	l := logic.NewListMessagesLogic(ctx, s.svcCtx)
	return l.ListMessages(in)
}
