// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inventory_GetInventory_FullMethodName         = "/inventory.Inventory/GetInventory"
	Inventory_UpdateInventory_FullMethodName      = "/inventory.Inventory/UpdateInventory"
	Inventory_DecreasePreInventory_FullMethodName = "/inventory.Inventory/DecreasePreInventory"
	Inventory_DecreaseInventory_FullMethodName    = "/inventory.Inventory/DecreaseInventory"
	Inventory_ReturnPreInventory_FullMethodName   = "/inventory.Inventory/ReturnPreInventory"
	Inventory_ReturnInventory_FullMethodName      = "/inventory.Inventory/ReturnInventory"
)

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	// GetInventory 查询库存，缓存不在，再去数据库查
	GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error)
	// UpdateInventory 增加库存，修改库存数量（直接修改）
	UpdateInventory(ctx context.Context, in *UpdateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	// DecreaseInventory 预扣减库存，此时并非真实扣除库存，而是在缓存进行--操作
	DecreasePreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	// DecreaseInventory 真实扣减库存（支付成功时）
	DecreaseInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	// ReturnPreInventory 退还预扣减的库存（）
	ReturnPreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
	// ReturnInventory 退还库存（支付失败时）
	ReturnInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) GetInventory(ctx context.Context, in *GetInventoryReq, opts ...grpc.CallOption) (*GetInventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInventoryResp)
	err := c.cc.Invoke(ctx, Inventory_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) UpdateInventory(ctx context.Context, in *UpdateInventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, Inventory_UpdateInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DecreasePreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, Inventory_DecreasePreInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DecreaseInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, Inventory_DecreaseInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ReturnPreInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, Inventory_ReturnPreInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ReturnInventory(ctx context.Context, in *InventoryReq, opts ...grpc.CallOption) (*InventoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InventoryResp)
	err := c.cc.Invoke(ctx, Inventory_ReturnInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility.
type InventoryServer interface {
	// GetInventory 查询库存，缓存不在，再去数据库查
	GetInventory(context.Context, *GetInventoryReq) (*GetInventoryResp, error)
	// UpdateInventory 增加库存，修改库存数量（直接修改）
	UpdateInventory(context.Context, *UpdateInventoryReq) (*InventoryResp, error)
	// DecreaseInventory 预扣减库存，此时并非真实扣除库存，而是在缓存进行--操作
	DecreasePreInventory(context.Context, *InventoryReq) (*InventoryResp, error)
	// DecreaseInventory 真实扣减库存（支付成功时）
	DecreaseInventory(context.Context, *InventoryReq) (*InventoryResp, error)
	// ReturnPreInventory 退还预扣减的库存（）
	ReturnPreInventory(context.Context, *InventoryReq) (*InventoryResp, error)
	// ReturnInventory 退还库存（支付失败时）
	ReturnInventory(context.Context, *InventoryReq) (*InventoryResp, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServer struct{}

func (UnimplementedInventoryServer) GetInventory(context.Context, *GetInventoryReq) (*GetInventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedInventoryServer) UpdateInventory(context.Context, *UpdateInventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInventory not implemented")
}
func (UnimplementedInventoryServer) DecreasePreInventory(context.Context, *InventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecreasePreInventory not implemented")
}
func (UnimplementedInventoryServer) DecreaseInventory(context.Context, *InventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecreaseInventory not implemented")
}
func (UnimplementedInventoryServer) ReturnPreInventory(context.Context, *InventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnPreInventory not implemented")
}
func (UnimplementedInventoryServer) ReturnInventory(context.Context, *InventoryReq) (*InventoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnInventory not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}
func (UnimplementedInventoryServer) testEmbeddedByValue()                   {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s grpc.ServiceRegistrar, srv InventoryServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inventory_ServiceDesc, srv)
}

func _Inventory_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetInventory(ctx, req.(*GetInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_UpdateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).UpdateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_UpdateInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).UpdateInventory(ctx, req.(*UpdateInventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DecreasePreInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DecreasePreInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_DecreasePreInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DecreasePreInventory(ctx, req.(*InventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DecreaseInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DecreaseInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_DecreaseInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DecreaseInventory(ctx, req.(*InventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ReturnPreInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ReturnPreInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_ReturnPreInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ReturnPreInventory(ctx, req.(*InventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ReturnInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InventoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ReturnInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inventory_ReturnInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ReturnInventory(ctx, req.(*InventoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Inventory_ServiceDesc is the grpc.ServiceDesc for Inventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _Inventory_GetInventory_Handler,
		},
		{
			MethodName: "UpdateInventory",
			Handler:    _Inventory_UpdateInventory_Handler,
		},
		{
			MethodName: "DecreasePreInventory",
			Handler:    _Inventory_DecreasePreInventory_Handler,
		},
		{
			MethodName: "DecreaseInventory",
			Handler:    _Inventory_DecreaseInventory_Handler,
		},
		{
			MethodName: "ReturnPreInventory",
			Handler:    _Inventory_ReturnPreInventory_Handler,
		},
		{
			MethodName: "ReturnInventory",
			Handler:    _Inventory_ReturnInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
