filebeat.inputs:
  - type: filestream
    id: go-mall-api-logs
    enabled: true
    paths:
      - /usr/share/filebeat/apis/*/logs/*/*.log
    fields:
      project: go-mall
      env: dev
      log_source: api_logs
    fields_under_root: true

  - type: filestream
    id: go-mall-rpc-logs
    enabled: true
    paths:
      - /usr/share/filebeat/services/*/logs/*/*.log
    fields:
      project: go-mall
      env: dev
      log_source: rpc_logs
    fields_under_root: true

processors:
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

logging.to_files: false