// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: services/aiagent/aiagent.proto

package aiagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiAgent_Chat_FullMethodName          = "/aiagent.AiAgent/Chat"
	AiAgent_ConfirmAction_FullMethodName = "/aiagent.AiAgent/ConfirmAction"
)

// AiAgentClient is the client API for AiAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiAgentClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
	ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
}

type aiAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAiAgentClient(cc grpc.ClientConnInterface) AiAgentClient {
	return &aiAgentClient{cc}
}

func (c *aiAgentClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiAgent_ServiceDesc.Streams[0], AiAgent_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiAgent_ChatClient = grpc.ServerStreamingClient[AgentEvent]

func (c *aiAgentClient) ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiAgent_ServiceDesc.Streams[1], AiAgent_ConfirmAction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfirmActionRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiAgent_ConfirmActionClient = grpc.ServerStreamingClient[AgentEvent]

// AiAgentServer is the server API for AiAgent service.
// All implementations must embed UnimplementedAiAgentServer
// for forward compatibility.
type AiAgentServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[AgentEvent]) error
	ConfirmAction(*ConfirmActionRequest, grpc.ServerStreamingServer[AgentEvent]) error
	mustEmbedUnimplementedAiAgentServer()
}

// UnimplementedAiAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiAgentServer struct{}

func (UnimplementedAiAgentServer) Chat(*ChatRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiAgentServer) ConfirmAction(*ConfirmActionRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ConfirmAction not implemented")
}
func (UnimplementedAiAgentServer) mustEmbedUnimplementedAiAgentServer() {}
func (UnimplementedAiAgentServer) testEmbeddedByValue()                 {}

// UnsafeAiAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiAgentServer will
// result in compilation errors.
type UnsafeAiAgentServer interface {
	mustEmbedUnimplementedAiAgentServer()
}

func RegisterAiAgentServer(s grpc.ServiceRegistrar, srv AiAgentServer) {
	// If the following call pancis, it indicates UnimplementedAiAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiAgent_ServiceDesc, srv)
}

func _AiAgent_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiAgentServer).Chat(m, &grpc.GenericServerStream[ChatRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiAgent_ChatServer = grpc.ServerStreamingServer[AgentEvent]

func _AiAgent_ConfirmAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfirmActionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiAgentServer).ConfirmAction(m, &grpc.GenericServerStream[ConfirmActionRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiAgent_ConfirmActionServer = grpc.ServerStreamingServer[AgentEvent]

// AiAgent_ServiceDesc is the grpc.ServiceDesc for AiAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiagent.AiAgent",
	HandlerType: (*AiAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AiAgent_Chat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConfirmAction",
			Handler:       _AiAgent_ConfirmAction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/aiagent/aiagent.proto",
}
