// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: services/aiagent/aiagent.proto

package aiagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Source         string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_services_aiagent_aiagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_aiagent_aiagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_services_aiagent_aiagent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AgentEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Tool           string                 `protobuf:"bytes,5,opt,name=tool,proto3" json:"tool,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DataJson       string                 `protobuf:"bytes,7,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	ConfirmationId string                 `protobuf:"bytes,8,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	Action         string                 `protobuf:"bytes,9,opt,name=action,proto3" json:"action,omitempty"`
	Summary        string                 `protobuf:"bytes,10,opt,name=summary,proto3" json:"summary,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Done           bool                   `protobuf:"varint,12,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_services_aiagent_aiagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_aiagent_aiagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_services_aiagent_aiagent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *AgentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentEvent) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *AgentEvent) GetConfirmationId() string {
	if x != nil {
		return x.ConfirmationId
	}
	return ""
}

func (x *AgentEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AgentEvent) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AgentEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Events        []*AgentEvent          `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_services_aiagent_aiagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_aiagent_aiagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_services_aiagent_aiagent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ChatResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ChatResponse) GetEvents() []*AgentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ConfirmActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConfirmationId string                 `protobuf:"bytes,3,opt,name=confirmation_id,json=confirmationId,proto3" json:"confirmation_id,omitempty"`
	Approved       bool                   `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmActionRequest) Reset() {
	*x = ConfirmActionRequest{}
	mi := &file_services_aiagent_aiagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionRequest) ProtoMessage() {}

func (x *ConfirmActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_aiagent_aiagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionRequest.ProtoReflect.Descriptor instead.
func (*ConfirmActionRequest) Descriptor() ([]byte, []int) {
	return file_services_aiagent_aiagent_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmActionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmActionRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConfirmActionRequest) GetConfirmationId() string {
	if x != nil {
		return x.ConfirmationId
	}
	return ""
}

func (x *ConfirmActionRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ConfirmActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Events        []*AgentEvent          `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmActionResponse) Reset() {
	*x = ConfirmActionResponse{}
	mi := &file_services_aiagent_aiagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmActionResponse) ProtoMessage() {}

func (x *ConfirmActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_aiagent_aiagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmActionResponse.ProtoReflect.Descriptor instead.
func (*ConfirmActionResponse) Descriptor() ([]byte, []int) {
	return file_services_aiagent_aiagent_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmActionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ConfirmActionResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ConfirmActionResponse) GetEvents() []*AgentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_services_aiagent_aiagent_proto protoreflect.FileDescriptor

const file_services_aiagent_aiagent_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/aiagent/aiagent.proto\x12\aaiagent\"\xa0\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xd9\x02\n" +
	"\n" +
	"AgentEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04tool\x18\x05 \x01(\tR\x04tool\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tdata_json\x18\a \x01(\tR\bdataJson\x12'\n" +
	"\x0fconfirmation_id\x18\b \x01(\tR\x0econfirmationId\x12\x16\n" +
	"\x06action\x18\t \x01(\tR\x06action\x12\x18\n" +
	"\asummary\x18\n" +
	" \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\x03R\texpiresAt\x12\x12\n" +
	"\x04done\x18\f \x01(\bR\x04done\"{\n" +
	"\fChatResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12+\n" +
	"\x06events\x18\x03 \x03(\v2\x13.aiagent.AgentEventR\x06events\"\x9d\x01\n" +
	"\x14ConfirmActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12'\n" +
	"\x0fconfirmation_id\x18\x03 \x01(\tR\x0econfirmationId\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapproved\"\x84\x01\n" +
	"\x15ConfirmActionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12+\n" +
	"\x06events\x18\x03 \x03(\v2\x13.aiagent.AgentEventR\x06events2\x8e\x01\n" +
	"\aAiAgent\x123\n" +
	"\x04Chat\x12\x14.aiagent.ChatRequest\x1a\x15.aiagent.ChatResponse\x12N\n" +
	"\rConfirmAction\x12\x1d.aiagent.ConfirmActionRequest\x1a\x1e.aiagent.ConfirmActionResponseB\vZ\t./aiagentb\x06proto3"

var (
	file_services_aiagent_aiagent_proto_rawDescOnce sync.Once
	file_services_aiagent_aiagent_proto_rawDescData []byte
)

func file_services_aiagent_aiagent_proto_rawDescGZIP() []byte {
	file_services_aiagent_aiagent_proto_rawDescOnce.Do(func() {
		file_services_aiagent_aiagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_aiagent_aiagent_proto_rawDesc), len(file_services_aiagent_aiagent_proto_rawDesc)))
	})
	return file_services_aiagent_aiagent_proto_rawDescData
}

var file_services_aiagent_aiagent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_aiagent_aiagent_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: aiagent.ChatRequest
	(*AgentEvent)(nil),            // 1: aiagent.AgentEvent
	(*ChatResponse)(nil),          // 2: aiagent.ChatResponse
	(*ConfirmActionRequest)(nil),  // 3: aiagent.ConfirmActionRequest
	(*ConfirmActionResponse)(nil), // 4: aiagent.ConfirmActionResponse
}
var file_services_aiagent_aiagent_proto_depIdxs = []int32{
	1, // 0: aiagent.ChatResponse.events:type_name -> aiagent.AgentEvent
	1, // 1: aiagent.ConfirmActionResponse.events:type_name -> aiagent.AgentEvent
	0, // 2: aiagent.AiAgent.Chat:input_type -> aiagent.ChatRequest
	3, // 3: aiagent.AiAgent.ConfirmAction:input_type -> aiagent.ConfirmActionRequest
	2, // 4: aiagent.AiAgent.Chat:output_type -> aiagent.ChatResponse
	4, // 5: aiagent.AiAgent.ConfirmAction:output_type -> aiagent.ConfirmActionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_aiagent_aiagent_proto_init() }
func file_services_aiagent_aiagent_proto_init() {
	if File_services_aiagent_aiagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_aiagent_aiagent_proto_rawDesc), len(file_services_aiagent_aiagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_aiagent_aiagent_proto_goTypes,
		DependencyIndexes: file_services_aiagent_aiagent_proto_depIdxs,
		MessageInfos:      file_services_aiagent_aiagent_proto_msgTypes,
	}.Build()
	File_services_aiagent_aiagent_proto = out.File
	file_services_aiagent_aiagent_proto_goTypes = nil
	file_services_aiagent_aiagent_proto_depIdxs = nil
}
