// Code generated by goctl. DO NOT EDIT.
package types

type CalculateCouponReq struct {
	CouponID string  `json:"coupon_id"`
	Items    []Items `json:"items"`
}

type CalculateCouponResp struct {
	OriginAmount   int64  `json:"origin_amount"` // 分
	FinalAmount    int64  `json:"final_amount"`
	DiscountAmount int64  `json:"discount_amount"`
	CouponType     string `json:"coupon_type"`
	IsUsable       bool   `json:"is_usable"`
	UnusableReason string `json:"unusable_reason"`
}

type CouponItemReq struct {
	CouponID string `json:"coupon_id"`
}

type CouponItemResp struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Type           uint8  `json:"type"`
	Value          string `json:"value"`
	MinAmount      string `json:"min_amount"`
	StartTime      string `json:"start_time"`
	EndTime        string `json:"end_time"`
	TotalCount     uint64 `json:"total_count"`
	RemainingCount uint64 `json:"remaining_count"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type CouponListReq struct {
	Page     int32 `json:"page,default=1"`
	PageSize int32 `json:"size,default=10"`
	Type     uint8 `json:"type,optional"` // 优惠卷类型
}

type CouponListResp struct {
	CouponList []CouponItemResp `json:"coupon_list"`
}

type CouponMy struct {
	ID        int32  `json:"id"`
	CouponID  string `json:"coupon_id"`
	Status    string `json:"status"`
	OrderID   string `json:"order_id"`
	UsedAt    string `json:"used_at"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CouponMyListResp struct {
	CouponList []CouponMy `json:"coupon_list"`
}

type CouponUsage struct {
	ID             int32  `json:"id"`
	PreOrderID     string `json:"pre_order_id"`
	OrderID        string `json:"order_id"`
	CouponID       string `json:"coupon_id"`
	UserID         int32  `json:"user_id"`
	CouponType     string `json:"coupon_type"`
	OriginValue    string `json:"origin_value"`
	DiscountAmount string `json:"discount_amount"`
	AppliedAt      string `json:"applied_at"`
}

type CouponUsageListResp struct {
	CouponUsageList []CouponUsage `json:"coupon_usage_list"`
}

type Items struct {
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}
