// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"github.com/leventsg/e-commerce-AI-system/apis/carts/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WithClientMiddleware, serverCtx.WrapperAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: CreateCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delete",
					Handler: DeleteCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: CartItemListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sub",
					Handler: SubCartItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/carts"),
	)
}
