// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package conversations

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiConversationsFieldNames          = builder.RawFieldNames(&AiConversations{})
	aiConversationsRows                = strings.Join(aiConversationsFieldNames, ",")
	aiConversationsRowsExpectAutoSet   = strings.Join(stringx.Remove(aiConversationsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	aiConversationsRowsWithPlaceHolder = strings.Join(stringx.Remove(aiConversationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAiConversationsIdPrefix = "cache:aiConversations:id:"
)

type (
	aiConversationsModel interface {
		Insert(ctx context.Context, data *AiConversations) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*AiConversations, error)
		Update(ctx context.Context, data *AiConversations) error
		Delete(ctx context.Context, id string) error
	}

	defaultAiConversationsModel struct {
		sqlc.CachedConn
		table string
	}

	AiConversations struct {
		Id        string    `db:"id"`      // 会话ID
		UserId    uint64    `db:"user_id"` // 用户ID
		Title     string    `db:"title"`   // 会话标题
		Status    string    `db:"status"`  // active/closed
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newAiConversationsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAiConversationsModel {
	return &defaultAiConversationsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`ai_conversations`",
	}
}

func (m *defaultAiConversationsModel) Delete(ctx context.Context, id string) error {
	aiConversationsIdKey := fmt.Sprintf("%s%v", cacheAiConversationsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiConversationsIdKey)
	return err
}

func (m *defaultAiConversationsModel) FindOne(ctx context.Context, id string) (*AiConversations, error) {
	aiConversationsIdKey := fmt.Sprintf("%s%v", cacheAiConversationsIdPrefix, id)
	var resp AiConversations
	err := m.QueryRowCtx(ctx, &resp, aiConversationsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiConversationsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiConversationsModel) Insert(ctx context.Context, data *AiConversations) (sql.Result, error) {
	aiConversationsIdKey := fmt.Sprintf("%s%v", cacheAiConversationsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, aiConversationsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Title, data.Status)
	}, aiConversationsIdKey)
	return ret, err
}

func (m *defaultAiConversationsModel) Update(ctx context.Context, data *AiConversations) error {
	aiConversationsIdKey := fmt.Sprintf("%s%v", cacheAiConversationsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, aiConversationsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Status, data.Id)
	}, aiConversationsIdKey)
	return err
}

func (m *defaultAiConversationsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAiConversationsIdPrefix, primary)
}

func (m *defaultAiConversationsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", aiConversationsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAiConversationsModel) tableName() string {
	return m.table
}
