// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type CartInfoResponse struct {
	Id        int32         `json:"id"`
	UserId    int32         `json:"user_id"`
	ProductId int32         `json:"product_id"`
	Quantity  int32         `json:"quantity"`
	Product   []interface{} `json:"product"`
}

type CartItemListResp struct {
	Total    int32               `json:"total"`
	CartInfo []*CartInfoResponse `json:"cart_info"`
}

type CreateCartReq struct {
	ProductId int32 `json:"product_id"`
}

type CreateCartResp struct {
	Id int32 `json:"id"`
}

type DeleteCartReq struct {
	ProductId int32 `json:"product_id"`
}

type DeleteCartResp struct {
	Success bool `json:"success"`
}

type SubCartReq struct {
	ProductId int32 `json:"product_id"`
}

type SubCartResp struct {
	Id int32 `json:"id"`
}

type UserInfo struct {
}
