// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================== 状态枚举定义 ==================
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED     OrderStatus = 0
	OrderStatus_ORDER_STATUS_CREATED         OrderStatus = 1 // 创建
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT OrderStatus = 2 // 待支付
	OrderStatus_ORDER_STATUS_PAID            OrderStatus = 3 // 已支付
	OrderStatus_ORDER_STATUS_COMPLETED       OrderStatus = 4 // 已完成 进行对账
	OrderStatus_ORDER_STATUS_CANCELLED       OrderStatus = 5 // 已取消
	OrderStatus_ORDER_STATUS_CLOSED          OrderStatus = 6 // 已关闭（超时）
	OrderStatus_ORDER_STATUS_REFUND          OrderStatus = 7 // 退款
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_CREATED",
		2: "ORDER_STATUS_PENDING_PAYMENT",
		3: "ORDER_STATUS_PAID",
		4: "ORDER_STATUS_COMPLETED",
		5: "ORDER_STATUS_CANCELLED",
		6: "ORDER_STATUS_CLOSED",
		7: "ORDER_STATUS_REFUND",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":     0,
		"ORDER_STATUS_CREATED":         1,
		"ORDER_STATUS_PENDING_PAYMENT": 2,
		"ORDER_STATUS_PAID":            3,
		"ORDER_STATUS_COMPLETED":       4,
		"ORDER_STATUS_CANCELLED":       5,
		"ORDER_STATUS_CLOSED":          6,
		"ORDER_STATUS_REFUND":          7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_NOT_PAID    PaymentStatus = 1 // 未支付 创建二维码但为支付
	PaymentStatus_PAYMENT_STATUS_PAYING      PaymentStatus = 2 // 支付中 进入支付状态
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 3 // 已支付
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 4 // 已过期
	PaymentStatus_PAYMENT_STATUS_REFUND      PaymentStatus = 5 // 退款
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_NOT_PAID",
		2: "PAYMENT_STATUS_PAYING",
		3: "PAYMENT_STATUS_PAID",
		4: "PAYMENT_STATUS_EXPIRED",
		5: "PAYMENT_STATUS_REFUND",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_NOT_PAID":    1,
		"PAYMENT_STATUS_PAYING":      2,
		"PAYMENT_STATUS_PAID":        3,
		"PAYMENT_STATUS_EXPIRED":     4,
		"PAYMENT_STATUS_REFUND":      5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_WECHAT_PAY                 PaymentMethod = 1
	PaymentMethod_ALIPAY                     PaymentMethod = 2
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "WECHAT_PAY",
		2: "ALIPAY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"WECHAT_PAY":                 1,
		"ALIPAY":                     2,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[2].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[2]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

// // --------------- 数据结构定义 ---------------
type Order struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OrderId    string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PreOrderId string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`
	UserId     uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 支付信息
	PaymentMethod PaymentMethod `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=order.PaymentMethod" json:"payment_method,omitempty"`
	TransactionId string        `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaidAt        int64         `protobuf:"varint,6,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	// 金额信息
	OriginalAmount int64 `protobuf:"varint,7,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"` // 单位：分
	DiscountAmount int64 `protobuf:"varint,8,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PayableAmount  int64 `protobuf:"varint,9,opt,name=payable_amount,json=payableAmount,proto3" json:"payable_amount,omitempty"`
	PaidAmount     int64 `protobuf:"varint,10,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	// 状态信息
	OrderStatus   OrderStatus   `protobuf:"varint,11,opt,name=order_status,json=orderStatus,proto3,enum=order.OrderStatus" json:"order_status,omitempty"`
	PaymentStatus PaymentStatus `protobuf:"varint,12,opt,name=payment_status,json=paymentStatus,proto3,enum=order.PaymentStatus" json:"payment_status,omitempty"`
	Reason        string        `protobuf:"bytes,13,opt,name=Reason,proto3" json:"Reason,omitempty"`
	// 时间信息
	ExpireTime    string `protobuf:"bytes,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	CreatedAt     string `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *Order) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Order) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Order) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

func (x *Order) GetOriginalAmount() int64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *Order) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Order) GetPayableAmount() int64 {
	if x != nil {
		return x.PayableAmount
	}
	return 0
}

func (x *Order) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *Order) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Order) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Order) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductDesc   string                 `protobuf:"bytes,5,opt,name=product_desc,json=productDesc,proto3" json:"product_desc,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,6,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"` // 单位：分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *OrderItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type OrderAddress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AddressId       uint64                 `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	RecipientName   string                 `protobuf:"bytes,2,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Province        string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City            string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	DetailedAddress string                 `protobuf:"bytes,6,opt,name=detailed_address,json=detailedAddress,proto3" json:"detailed_address,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OrderId         string                 `protobuf:"bytes,9,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderAddress) Reset() {
	*x = OrderAddress{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddress) ProtoMessage() {}

func (x *OrderAddress) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddress.ProtoReflect.Descriptor instead.
func (*OrderAddress) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderAddress) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *OrderAddress) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *OrderAddress) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *OrderAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *OrderAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderAddress) GetDetailedAddress() string {
	if x != nil {
		return x.DetailedAddress
	}
	return ""
}

func (x *OrderAddress) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderAddress) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderAddress) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PaymentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 支付平台流水号
	PaidAmount    int64                  `protobuf:"varint,2,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`         // 实际支付金额（分）
	PaidAt        int64                  `protobuf:"varint,3,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                     // 支付时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResult) Reset() {
	*x = PaymentResult{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResult) ProtoMessage() {}

func (x *PaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResult.ProtoReflect.Descriptor instead.
func (*PaymentResult) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResult) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentResult) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *PaymentResult) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

// --------------- 请求 ---------------
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用于权限校验
	CancelReason  string                 `protobuf:"bytes,3,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"` // 取消原因（可选）
	Initiative    bool                   `protobuf:"varint,4,opt,name=initiative,proto3" json:"initiative,omitempty"`                        // 是否主动取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *CancelOrderRequest) GetInitiative() bool {
	if x != nil {
		return x.Initiative
	}
	return false
}

type UpdateOrder2PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrder2PaymentRequest) Reset() {
	*x = UpdateOrder2PaymentRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrder2PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrder2PaymentRequest) ProtoMessage() {}

func (x *UpdateOrder2PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrder2PaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrder2PaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrder2PaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrder2PaymentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HandlePaymentTimeoutOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlePaymentTimeoutOrderRequest) Reset() {
	*x = HandlePaymentTimeoutOrderRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlePaymentTimeoutOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlePaymentTimeoutOrderRequest) ProtoMessage() {}

func (x *HandlePaymentTimeoutOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlePaymentTimeoutOrderRequest.ProtoReflect.Descriptor instead.
func (*HandlePaymentTimeoutOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *HandlePaymentTimeoutOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HandlePaymentTimeoutOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandlePaymentTimeoutOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreOrderId    string                 `protobuf:"bytes,1,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"` // 必须有效的预订单ID
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 用户身份验证
	CouponId      string                 `protobuf:"bytes,3,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=order.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderRequest) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *CreateOrderRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreateOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type UpdateOrder2PaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentResult *PaymentResult         `protobuf:"bytes,2,opt,name=payment_result,json=paymentResult,proto3" json:"payment_result,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrder2PaymentSuccessRequest) Reset() {
	*x = UpdateOrder2PaymentSuccessRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrder2PaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrder2PaymentSuccessRequest) ProtoMessage() {}

func (x *UpdateOrder2PaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrder2PaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrder2PaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrder2PaymentSuccessRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrder2PaymentSuccessRequest) GetPaymentResult() *PaymentResult {
	if x != nil {
		return x.PaymentResult
	}
	return nil
}

func (x *UpdateOrder2PaymentSuccessRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 普通用户传实际ID，管理端传0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	UserId        uint32                               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StatusFilter  *ListOrdersRequest_OrderStatusFilter `protobuf:"bytes,2,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	Pagination    *ListOrdersRequest_Pagination        `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetStatusFilter() *ListOrdersRequest_OrderStatusFilter {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListOrdersRequest) GetPagination() *ListOrdersRequest_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// --------------- response ---------------
type OrderDetail2PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail2PaymentResponse) Reset() {
	*x = OrderDetail2PaymentResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail2PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail2PaymentResponse) ProtoMessage() {}

func (x *OrderDetail2PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail2PaymentResponse.ProtoReflect.Descriptor instead.
func (*OrderDetail2PaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderDetail2PaymentResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OrderDetail2PaymentResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *OrderDetail2PaymentResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Address       *OrderAddress          `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailResponse) Reset() {
	*x = OrderDetailResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailResponse) ProtoMessage() {}

func (x *OrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailResponse.ProtoReflect.Descriptor instead.
func (*OrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *OrderDetailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OrderDetailResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *OrderDetailResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderDetailResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderDetailResponse) GetAddress() *OrderAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Orders        []*Order               `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListOrdersResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type EmptyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRes) Reset() {
	*x = EmptyRes{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRes) ProtoMessage() {}

func (x *EmptyRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRes.ProtoReflect.Descriptor instead.
func (*EmptyRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *EmptyRes) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmptyRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type ListOrdersRequest_OrderStatusFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []OrderStatus          `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=order.OrderStatus" json:"statuses,omitempty"` // 空列表表示不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest_OrderStatusFilter) Reset() {
	*x = ListOrdersRequest_OrderStatusFilter{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest_OrderStatusFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest_OrderStatusFilter) ProtoMessage() {}

func (x *ListOrdersRequest_OrderStatusFilter) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest_OrderStatusFilter.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest_OrderStatusFilter) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ListOrdersRequest_OrderStatusFilter) GetStatuses() []OrderStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListOrdersRequest_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 从1开始
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 最大100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest_Pagination) Reset() {
	*x = ListOrdersRequest_Pagination{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest_Pagination) ProtoMessage() {}

func (x *ListOrdersRequest_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest_Pagination.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest_Pagination) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 1}
}

func (x *ListOrdersRequest_Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\xdf\x04\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12;\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x14.order.PaymentMethodR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x17\n" +
	"\apaid_at\x18\x06 \x01(\x03R\x06paidAt\x12'\n" +
	"\x0foriginal_amount\x18\a \x01(\x03R\x0eoriginalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\b \x01(\x03R\x0ediscountAmount\x12%\n" +
	"\x0epayable_amount\x18\t \x01(\x03R\rpayableAmount\x12\x1f\n" +
	"\vpaid_amount\x18\n" +
	" \x01(\x03R\n" +
	"paidAmount\x125\n" +
	"\forder_status\x18\v \x01(\x0e2\x12.order.OrderStatusR\vorderStatus\x12;\n" +
	"\x0epayment_status\x18\f \x01(\x0e2\x14.order.PaymentStatusR\rpaymentStatus\x12\x16\n" +
	"\x06Reason\x18\r \x01(\tR\x06Reason\x12\x1f\n" +
	"\vexpire_time\x18\x0e \x01(\tR\n" +
	"expireTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"\xc4\x01\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_desc\x18\x05 \x01(\tR\vproductDesc\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x06 \x01(\x03R\tunitPrice\"\xab\x02\n" +
	"\fOrderAddress\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\x04R\taddressId\x12%\n" +
	"\x0erecipient_name\x18\x02 \x01(\tR\rrecipientName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12)\n" +
	"\x10detailed_address\x18\x06 \x01(\tR\x0fdetailedAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x19\n" +
	"\border_id\x18\t \x01(\tR\aorderId\"p\n" +
	"\rPaymentResult\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vpaid_amount\x18\x02 \x01(\x03R\n" +
	"paidAmount\x12\x17\n" +
	"\apaid_at\x18\x03 \x01(\x03R\x06paidAt\"\x8d\x01\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rcancel_reason\x18\x03 \x01(\tR\fcancelReason\x12\x1e\n" +
	"\n" +
	"initiative\x18\x04 \x01(\bR\n" +
	"initiative\"P\n" +
	"\x1aUpdateOrder2PaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"n\n" +
	" HandlePaymentTimeoutOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xc8\x01\n" +
	"\x12CreateOrderRequest\x12 \n" +
	"\fpre_order_id\x18\x01 \x01(\tR\n" +
	"preOrderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x03 \x01(\tR\bcouponId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\x05R\taddressId\x12;\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x14.order.PaymentMethodR\rpaymentMethod\"\x94\x01\n" +
	"!UpdateOrder2PaymentSuccessRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12;\n" +
	"\x0epayment_result\x18\x02 \x01(\v2\x14.order.PaymentResultR\rpaymentResult\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\"E\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\xc6\x02\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12O\n" +
	"\rstatus_filter\x18\x02 \x01(\v2*.order.ListOrdersRequest.OrderStatusFilterR\fstatusFilter\x12C\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2#.order.ListOrdersRequest.PaginationR\n" +
	"pagination\x1aC\n" +
	"\x11OrderStatusFilter\x12.\n" +
	"\bstatuses\x18\x01 \x03(\x0e2\x12.order.OrderStatusR\bstatuses\x1a=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x1bOrderDetail2PaymentResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\"\n" +
	"\x05order\x18\x03 \x01(\v2\f.order.OrderR\x05order\"\xd0\x01\n" +
	"\x13OrderDetailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\"\n" +
	"\x05order\x18\x03 \x01(\v2\f.order.OrderR\x05order\x12&\n" +
	"\x05items\x18\x04 \x03(\v2\x10.order.OrderItemR\x05items\x12-\n" +
	"\aaddress\x18\x05 \x01(\v2\x13.order.OrderAddressR\aaddress\"z\n" +
	"\x12ListOrdersResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12$\n" +
	"\x06orders\x18\x03 \x03(\v2\f.order.OrderR\x06orders\"J\n" +
	"\bEmptyRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg*\xe8\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x02\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05\x12\x17\n" +
	"\x13ORDER_STATUS_CLOSED\x10\x06\x12\x17\n" +
	"\x13ORDER_STATUS_REFUND\x10\a*\xb7\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAYMENT_STATUS_NOT_PAID\x10\x01\x12\x19\n" +
	"\x15PAYMENT_STATUS_PAYING\x10\x02\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x04\x12\x19\n" +
	"\x15PAYMENT_STATUS_REFUND\x10\x05*K\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"WECHAT_PAY\x10\x01\x12\n" +
	"\n" +
	"\x06ALIPAY\x10\x022\xe0\x06\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.OrderDetailResponse\x12A\n" +
	"\x13CreateOrderRollback\x12\x19.order.CreateOrderRequest\x1a\x0f.order.EmptyRes\x129\n" +
	"\vCancelOrder\x12\x19.order.CancelOrderRequest\x1a\x0f.order.EmptyRes\x12>\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x1a.order.OrderDetailResponse\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponse\x12W\n" +
	"\x1aUpdateOrder2PaymentSuccess\x12(.order.UpdateOrder2PaymentSuccessRequest\x1a\x0f.order.EmptyRes\x12_\n" +
	"\"UpdateOrder2PaymentSuccessRollback\x12(.order.UpdateOrder2PaymentSuccessRequest\x1a\x0f.order.EmptyRes\x12O\n" +
	"\x19UpdateOrder2PaymentStatus\x12!.order.UpdateOrder2PaymentRequest\x1a\x0f.order.EmptyRes\x12W\n" +
	"!UpdateOrder2PaymentStatusRollback\x12!.order.UpdateOrder2PaymentRequest\x1a\x0f.order.EmptyRes\x12N\n" +
	"\x10GetOrder2Payment\x12\x16.order.GetOrderRequest\x1a\".order.OrderDetail2PaymentResponse\x12U\n" +
	"\x19HandlePaymentTimeoutOrder\x12'.order.HandlePaymentTimeoutOrderRequest\x1a\x0f.order.EmptyResB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_order_proto_goTypes = []any{
	(OrderStatus)(0),                            // 0: order.OrderStatus
	(PaymentStatus)(0),                          // 1: order.PaymentStatus
	(PaymentMethod)(0),                          // 2: order.PaymentMethod
	(*Order)(nil),                               // 3: order.Order
	(*OrderItem)(nil),                           // 4: order.OrderItem
	(*OrderAddress)(nil),                        // 5: order.OrderAddress
	(*PaymentResult)(nil),                       // 6: order.PaymentResult
	(*CancelOrderRequest)(nil),                  // 7: order.CancelOrderRequest
	(*UpdateOrder2PaymentRequest)(nil),          // 8: order.UpdateOrder2PaymentRequest
	(*HandlePaymentTimeoutOrderRequest)(nil),    // 9: order.HandlePaymentTimeoutOrderRequest
	(*CreateOrderRequest)(nil),                  // 10: order.CreateOrderRequest
	(*UpdateOrder2PaymentSuccessRequest)(nil),   // 11: order.UpdateOrder2PaymentSuccessRequest
	(*GetOrderRequest)(nil),                     // 12: order.GetOrderRequest
	(*ListOrdersRequest)(nil),                   // 13: order.ListOrdersRequest
	(*OrderDetail2PaymentResponse)(nil),         // 14: order.OrderDetail2PaymentResponse
	(*OrderDetailResponse)(nil),                 // 15: order.OrderDetailResponse
	(*ListOrdersResponse)(nil),                  // 16: order.ListOrdersResponse
	(*EmptyRes)(nil),                            // 17: order.EmptyRes
	(*ListOrdersRequest_OrderStatusFilter)(nil), // 18: order.ListOrdersRequest.OrderStatusFilter
	(*ListOrdersRequest_Pagination)(nil),        // 19: order.ListOrdersRequest.Pagination
}
var file_order_proto_depIdxs = []int32{
	2,  // 0: order.Order.payment_method:type_name -> order.PaymentMethod
	0,  // 1: order.Order.order_status:type_name -> order.OrderStatus
	1,  // 2: order.Order.payment_status:type_name -> order.PaymentStatus
	2,  // 3: order.CreateOrderRequest.payment_method:type_name -> order.PaymentMethod
	6,  // 4: order.UpdateOrder2PaymentSuccessRequest.payment_result:type_name -> order.PaymentResult
	18, // 5: order.ListOrdersRequest.status_filter:type_name -> order.ListOrdersRequest.OrderStatusFilter
	19, // 6: order.ListOrdersRequest.pagination:type_name -> order.ListOrdersRequest.Pagination
	3,  // 7: order.OrderDetail2PaymentResponse.order:type_name -> order.Order
	3,  // 8: order.OrderDetailResponse.order:type_name -> order.Order
	4,  // 9: order.OrderDetailResponse.items:type_name -> order.OrderItem
	5,  // 10: order.OrderDetailResponse.address:type_name -> order.OrderAddress
	3,  // 11: order.ListOrdersResponse.orders:type_name -> order.Order
	0,  // 12: order.ListOrdersRequest.OrderStatusFilter.statuses:type_name -> order.OrderStatus
	10, // 13: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	10, // 14: order.OrderService.CreateOrderRollback:input_type -> order.CreateOrderRequest
	7,  // 15: order.OrderService.CancelOrder:input_type -> order.CancelOrderRequest
	12, // 16: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	13, // 17: order.OrderService.ListOrders:input_type -> order.ListOrdersRequest
	11, // 18: order.OrderService.UpdateOrder2PaymentSuccess:input_type -> order.UpdateOrder2PaymentSuccessRequest
	11, // 19: order.OrderService.UpdateOrder2PaymentSuccessRollback:input_type -> order.UpdateOrder2PaymentSuccessRequest
	8,  // 20: order.OrderService.UpdateOrder2PaymentStatus:input_type -> order.UpdateOrder2PaymentRequest
	8,  // 21: order.OrderService.UpdateOrder2PaymentStatusRollback:input_type -> order.UpdateOrder2PaymentRequest
	12, // 22: order.OrderService.GetOrder2Payment:input_type -> order.GetOrderRequest
	9,  // 23: order.OrderService.HandlePaymentTimeoutOrder:input_type -> order.HandlePaymentTimeoutOrderRequest
	15, // 24: order.OrderService.CreateOrder:output_type -> order.OrderDetailResponse
	17, // 25: order.OrderService.CreateOrderRollback:output_type -> order.EmptyRes
	17, // 26: order.OrderService.CancelOrder:output_type -> order.EmptyRes
	15, // 27: order.OrderService.GetOrder:output_type -> order.OrderDetailResponse
	16, // 28: order.OrderService.ListOrders:output_type -> order.ListOrdersResponse
	17, // 29: order.OrderService.UpdateOrder2PaymentSuccess:output_type -> order.EmptyRes
	17, // 30: order.OrderService.UpdateOrder2PaymentSuccessRollback:output_type -> order.EmptyRes
	17, // 31: order.OrderService.UpdateOrder2PaymentStatus:output_type -> order.EmptyRes
	17, // 32: order.OrderService.UpdateOrder2PaymentStatusRollback:output_type -> order.EmptyRes
	14, // 33: order.OrderService.GetOrder2Payment:output_type -> order.OrderDetail2PaymentResponse
	17, // 34: order.OrderService.HandlePaymentTimeoutOrder:output_type -> order.EmptyRes
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
