// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: aiagent.proto

package aiagentclient

import (
	"context"

	"github.com/leventsg/e-commerce-AI-system/services/aiagent/aiagent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentEvent            = aiagent.AgentEvent
	ChatRequest           = aiagent.ChatRequest
	ChatResponse          = aiagent.ChatResponse
	ConfirmActionRequest  = aiagent.ConfirmActionRequest
	ConfirmActionResponse = aiagent.ConfirmActionResponse

	AiAgent interface {
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
		ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (*ConfirmActionResponse, error)
	}

	defaultAiAgent struct {
		cli zrpc.Client
	}
)

func NewAiAgent(cli zrpc.Client) AiAgent {
	return &defaultAiAgent{
		cli: cli,
	}
}

func (m *defaultAiAgent) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	client := aiagent.NewAiAgentClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

func (m *defaultAiAgent) ConfirmAction(ctx context.Context, in *ConfirmActionRequest, opts ...grpc.CallOption) (*ConfirmActionResponse, error) {
	client := aiagent.NewAiAgentClient(m.cli.Conn())
	return client.ConfirmAction(ctx, in, opts...)
}
